export interface CountrySeoProfile {
  language: string;
  title: string;
  description: string;
  keywords: string[];
  hazards: string[];
  intro: string;
  cta: string;
}

export const COUNTRY_SEO: Record<string, CountrySeoProfile> = {
  PL:{language:'pl',title:'Geologia, grunt i zagrożenia działki w Polsce',description:'Sprawdź publiczne informacje o geologii, gruncie, wodach i zagrożeniach terenu przed zakupem lub budową.',keywords:['geologia działki','warunki gruntowe','osuwiska','powodzie','szkody górnicze'],hazards:['Geologia i warunki gruntowe','Osuwiska i stateczność zboczy','Powodzie i wody','Szkody górnicze i osiadanie'],intro:'GroundSurf łączy publiczne dane o wybranej lokalizacji i pokazuje, co wiadomo, co może to oznaczać oraz co warto jeszcze potwierdzić.',cta:'Wyszukaj lokalizację'},
  DE:{language:'de',title:'Grundstück, Baugrund und Gefahren in Deutschland prüfen',description:'Öffentliche Informationen zu Geologie, Baugrund, Grundwasser, Hochwasser, Hanginstabilität und Altlasten prüfen.',keywords:['Grundstück Geologie','Baugrund','Hochwasser','Hangrutschung','Altlasten'],hazards:['Geologie und Baugrund','Hochwasser und Überschwemmung','Hangrutschungen und Hangstabilität','Altlasten und frühere Nutzung'],intro:'GroundSurf verbindet öffentliche Informationen zum ausgewählten Standort und zeigt, was bekannt ist, was es bedeuten kann und was noch bestätigt werden sollte.',cta:'Standort suchen'},
  FR:{language:'fr',title:'Géologie, sol et risques liés au terrain en France',description:'Explorez les informations publiques sur la géologie, les sols, l’eau et les risques liés à un terrain avant d’acheter ou de construire.',keywords:['géologie terrain','risques naturels','glissement de terrain','inondation','argiles'],hazards:['Géologie et nature du sol','Inondation et ruissellement','Glissements de terrain et stabilité des pentes','Retrait-gonflement des argiles'],intro:'GroundSurf rassemble les informations publiques disponibles sur un site et distingue les faits connus, leur interprétation et les points à confirmer.',cta:'Rechercher un lieu'},
  IT:{language:'it',title:'Geologia, terreno e rischi del suolo in Italia',description:'Esplora le informazioni pubbliche su geologia, terreno, acqua, frane, alluvioni e altri rischi prima di acquistare o costruire.',keywords:['geologia terreno','rischio frana','alluvione','subsidenza','terremoto','vulcano'],hazards:['Geologia e condizioni del terreno','Frane e stabilità dei versanti','Alluvioni e acqua','Subsidenza e cedimenti','Rischi sismici e vulcanici'],intro:'GroundSurf raccoglie le informazioni pubbliche disponibili sul luogo scelto e distingue ciò che è noto da ciò che deve ancora essere verificato.',cta:'Cerca una posizione'},
  ES:{language:'es',title:'Geología, suelo y riesgos del terreno en España',description:'Explora información pública sobre geología, suelo, agua, inundaciones, deslizamientos y otras condiciones del terreno.',keywords:['geología parcela','riesgos naturales','inundaciones','deslizamientos','subsidencia'],hazards:['Geología y suelo','Inundaciones','Deslizamientos y estabilidad de laderas','Subsidencia y erosión'],intro:'GroundSurf reúne información pública sobre la ubicación elegida y explica qué se conoce, qué puede significar y qué queda por confirmar.',cta:'Buscar una ubicación'},
  NL:{language:'nl',title:'Bodem, ondergrond en risico’s van een perceel in Nederland',description:'Bekijk openbare informatie over bodem, ondergrond, grondwater, overstroming, bodemdaling en bouwgrond.',keywords:['bodem perceel','geologie','grondwater','overstroming','bodemdaling'],hazards:['Bodem en ondergrond','Grondwater en overstroming','Bodemdaling en zetting','Fundering en bouwgrond'],intro:'GroundSurf brengt openbare informatie over de gekozen locatie samen en maakt duidelijk wat bekend is en wat nog moet worden onderzocht.',cta:'Zoek een locatie'},
  BE:{language:'nl',title:'Bodem, geologie en terreingebonden risico’s in België',description:'Bekijk openbare informatie over bodem, geologie, water, overstroming en bouwgrond in België.',keywords:['bodem perceel','geologie België','overstroming','grondwater','bouwgrond'],hazards:['Bodem en geologie','Overstroming en water','Stabiliteit en zetting','Bouwgrond en fundering'],intro:'GroundSurf verzamelt openbare informatie over de gekozen locatie en onderscheidt beschikbare aanwijzingen van punten die nog moeten worden bevestigd.',cta:'Zoek een locatie'},
  AT:{language:'de',title:'Grundstück, Baugrund und Naturgefahren in Österreich',description:'Prüfen Sie Geologie, Baugrund, Hochwasser, Hanginstabilität und andere Naturgefahren vor dem Bauen.',keywords:['Baugrund Österreich','Geologie Grundstück','Hochwasser','Hangrutschung'],hazards:['Geologie und Baugrund','Hochwasser und Gewässer','Hanginstabilität und Massenbewegungen','Gebirgs- und Naturgefahren'],intro:'GroundSurf verbindet öffentliche Standortinformationen und zeigt, welche Hinweise vorhanden sind und was noch untersucht werden sollte.',cta:'Standort suchen'},
  SE:{language:'sv',title:'Geologi, markförhållanden och markrisker i Sverige',description:'Utforska offentlig information om geologi, jordarter, grundvatten, översvämning, ras och skred.',keywords:['geologi tomt','markförhållanden','översvämning','ras','skred'],hazards:['Geologi och jordarter','Översvämning','Ras och skred','Sättningar och markförhållanden'],intro:'GroundSurf samlar offentlig information om den valda platsen och visar vad som är känt och vad som behöver bekräftas.',cta:'Sök en plats'},
  IE:{language:'en',title:'Land geology, ground conditions and property hazards in Ireland',description:'Explore public evidence about geology, ground conditions, flooding, landslides, radon and groundwater in Ireland.',keywords:['land geology Ireland','flood risk','landslides','radon','groundwater'],hazards:['Geology and ground conditions','Flooding and surface water','Landslides and slope conditions','Radon and groundwater'],intro:'GroundSurf brings public evidence about a selected location together and separates known evidence from interpretation and questions that still need checking.',cta:'Search a location'},
  FI:{language:'fi',title:'Tontin maaperä, geologia ja maaperäriskit Suomessa',description:'Tutustu tontin geologiaan, maaperään, pohjaveteen, tulviin ja rakennettavuuteen liittyvään julkiseen tietoon.',keywords:['tontin maaperä','geologia','tulva','pohjavesi','sortuma'],hazards:['Kallioperä ja maaperä','Pohjavesi ja tulvat','Rinteet ja sortumat','Rakennettavuus ja painumat'],intro:'GroundSurf kokoaa valitusta sijainnista saatavilla olevan julkisen tiedon ja erottaa tunnetut tiedot asioista, jotka on vielä varmistettava.',cta:'Etsi sijainti'},
  PT:{language:'pt',title:'Geologia, solo e riscos do terreno em Portugal',description:'Explore informação pública sobre geologia, solo, água, inundações, deslizamentos e erosão em Portugal.',keywords:['geologia terreno Portugal','inundação','deslizamentos','erosão','águas subterrâneas'],hazards:['Geologia e solo','Inundações e água','Deslizamentos e estabilidade de encostas','Erosão e subsidência'],intro:'O GroundSurf reúne informação pública sobre o local escolhido e distingue o que é conhecido do que ainda precisa de confirmação.',cta:'Pesquisar uma localização'},
  DK:{language:'da',title:'Jordbund, geologi og risici ved en grund i Danmark',description:'Undersøg offentlig information om jordbund, geologi, grundvand, oversvømmelse, erosion og byggegrund.',keywords:['jordbund grund','geologi','oversvømmelse','grundvand','sætninger'],hazards:['Jordbund og geologi','Grundvand og oversvømmelse','Kyst- og erosionsforhold','Sætninger og byggegrund'],intro:'GroundSurf samler offentlige oplysninger om den valgte placering og viser, hvad der er kendt, og hvad der bør undersøges nærmere.',cta:'Søg efter en placering'},
  CZ:{language:'cs',title:'Geologie, půda a rizika pozemku v Česku',description:'Prozkoumejte veřejné informace o geologii, půdě, povodních, sesuvech, podzemní vodě a podloží.',keywords:['geologie pozemku','povodně','sesuvy','podzemní voda','radon'],hazards:['Geologie a půda','Povodně a voda','Sesuvy a stabilita svahů','Podzemní voda a radon'],intro:'GroundSurf shromažďuje veřejné informace o vybraném místě a odděluje známé údaje od toho, co je třeba dále ověřit.',cta:'Vyhledat místo'},
  HU:{language:'hu',title:'Telek földtana, talaja és kockázatai Magyarországon',description:'Fedezze fel a telek földtani, talajtani, vízügyi és árvízi információit építés vagy vásárlás előtt.',keywords:['telek geológia','talaj','árvíz','belvíz','talajvíz','süllyedés'],hazards:['Földtan és talaj','Árvíz és belvíz','Talajvíz','Süllyedés és építési talaj'],intro:'A GroundSurf összegyűjti a kiválasztott hely nyilvános adatait, és megmutatja, mi ismert és mit kell még ellenőrizni.',cta:'Helyszín keresése'},
  RO:{language:'ro',title:'Geologia, solul și riscurile unui teren în România',description:'Explorează informații publice despre geologie, sol, inundații, alunecări, apă subterană și tasare.',keywords:['geologia terenului','alunecări de teren','inundații','apă subterană','tasare'],hazards:['Geologie și sol','Inundații și apă','Alunecări de teren și stabilitatea versanților','Tasare și condiții de fundare'],intro:'GroundSurf reunește informațiile publice disponibile pentru locația aleasă și separă datele cunoscute de aspectele care trebuie confirmate.',cta:'Caută o locație'},
  SK:{language:'sk',title:'Geológia, pôda a riziká pozemku na Slovensku',description:'Preskúmajte verejné informácie o geológii, pôde, povodniach, zosuvoch, podzemnej vode a podloží.',keywords:['geológia pozemku','zosuvy','povodne','podzemná voda','radón'],hazards:['Geológia a pôda','Povodne a voda','Zosuvy a stabilita svahov','Podzemná voda a radón'],intro:'GroundSurf zhromažďuje verejné informácie o vybranej lokalite a oddeľuje známe údaje od toho, čo treba ešte overiť.',cta:'Vyhľadať lokalitu'},
  HR:{language:'hr',title:'Geologija, tlo i rizici zemljišta u Hrvatskoj',description:'Istražite javne podatke o geologiji, tlu, poplavama, klizištima, kršu i podzemnim vodama.',keywords:['geologija zemljišta','klizišta','poplave','krš','podzemne vode'],hazards:['Geologija i tlo','Poplave i vode','Klizišta i stabilnost padina','Krš, ponori i podzemne vode'],intro:'GroundSurf okuplja javno dostupne podatke o odabranoj lokaciji i razlikuje poznate informacije od onoga što još treba potvrditi.',cta:'Pretraži lokaciju'},
  GR:{language:'el',title:'Γεωλογία, έδαφος και κίνδυνοι ενός ακινήτου στην Ελλάδα',description:'Εξερευνήστε δημόσια στοιχεία για τη γεωλογία, το έδαφος, τις κατολισθήσεις, τις πλημμύρες και τη σεισμικότητα.',keywords:['γεωλογία οικοπέδου','κατολισθήσεις','πλημμύρες','σεισμός','υπόγεια νερά'],hazards:['Γεωλογία και έδαφος','Κατολισθήσεις και ευστάθεια πρανών','Πλημμύρες και νερά','Σεισμικοί κίνδυνοι'],intro:'Το GroundSurf συγκεντρώνει τα διαθέσιμα δημόσια στοιχεία για την επιλεγμένη τοποθεσία και ξεχωρίζει όσα είναι γνωστά από όσα χρειάζονται επιβεβαίωση.',cta:'Αναζήτηση τοποθεσίας'},
  EE:{language:'et',title:'Maa, pinnase ja geoloogiliste riskide kontroll Eestis',description:'Uurige avalikku teavet krundi geoloogia, pinnase, põhjavee, üleujutuste ja maalihete kohta.',keywords:['krundi geoloogia','pinnas','üleujutus','põhjavesi','maalihe'],hazards:['Geoloogia ja pinnas','Üleujutused ja põhjavesi','Nõlvad ja maalihked','Ehitustingimused ja vajumine'],intro:'GroundSurf koondab valitud asukoha avaliku teabe ning näitab, mis on teada ja mida tuleks veel kontrollida.',cta:'Otsi asukohta'},
  LV:{language:'lv',title:'Zemes ģeoloģija, grunts un riski Latvijā',description:'Izpētiet publiski pieejamu informāciju par zemes gabala ģeoloģiju, grunti, plūdiem, gruntsūdeņiem un nogāzēm.',keywords:['zemes gabala ģeoloģija','grunts','plūdi','gruntsūdeņi','noslīdeņi'],hazards:['Ģeoloģija un grunts','Plūdi un ūdens','Nogāžu stabilitāte un noslīdeņi','Grunts apstākļi būvniecībai'],intro:'GroundSurf apkopo publisko informāciju par izvēlēto vietu un nošķir zināmos datus no jautājumiem, kas vēl jāapstiprina.',cta:'Meklēt atrašanās vietu'},
  LT:{language:'lt',title:'Sklypo geologija, gruntas ir rizikos Lietuvoje',description:'Ištirkite viešą informaciją apie sklypo geologiją, gruntą, potvynius, požeminį vandenį ir nuošliaužas.',keywords:['sklypo geologija','gruntas','potvyniai','požeminis vanduo','nuošliaužos'],hazards:['Geologija ir gruntas','Potvyniai ir vanduo','Šlaitų stabilumas ir nuošliaužos','Grunto sąlygos statybai'],intro:'GroundSurf surenka viešai prieinamą informaciją apie pasirinktą vietą ir parodo, kas žinoma ir ką dar reikia patikrinti.',cta:'Ieškoti vietos'},
  LU:{language:'fr',title:'Géologie, sol et risques liés à un terrain au Luxembourg',description:'Explorez les informations publiques sur la géologie, le sol, l’eau, les inondations et la stabilité des terrains.',keywords:['géologie terrain Luxembourg','inondation','sol','eau souterraine','glissement'],hazards:['Géologie et sol','Inondation et eau','Stabilité des terrains','Conditions de fondation'],intro:'GroundSurf rassemble les informations publiques disponibles sur le lieu choisi et distingue les éléments connus des points à confirmer.',cta:'Rechercher un lieu'},
  CY:{language:'el',title:'Γεωλογία, έδαφος και κίνδυνοι γης στην Κύπρο',description:'Εξερευνήστε δημόσια στοιχεία για γεωλογία, έδαφος, πλημμύρες, κατολισθήσεις, σεισμούς και υπόγεια νερά στην Κύπρο.',keywords:['γεωλογία οικοπέδου Κύπρος','πλημμύρες','σεισμός','κατολισθήσεις','υπόγεια νερά'],hazards:['Γεωλογία και έδαφος','Πλημμύρες και νερά','Κατολισθήσεις και ευστάθεια πρανών','Σεισμικοί κίνδυνοι'],intro:'Το GroundSurf συγκεντρώνει τα διαθέσιμα δημόσια στοιχεία για την επιλεγμένη τοποθεσία και δείχνει τι χρειάζεται περαιτέρω έλεγχο.',cta:'Αναζήτηση τοποθεσίας'},
  MT:{language:'mt',title:'Ġeoloġija, ħamrija u riskji tal-art f’Malta',description:'Esplora informazzjoni pubblika dwar il-ġeoloġija, il-ħamrija, l-għargħar, l-erożjoni u l-ilma ta’ taħt l-art.',keywords:['ġeoloġija art Malta','għargħar','erożjoni','ilma ta’ taħt l-art','kostruzzjoni'],hazards:['Ġeoloġija u ħamrija','Għargħar u ilma','Erożjoni u stabbiltà tal-art','Kundizzjonijiet għall-kostruzzjoni'],intro:'GroundSurf jiġbor informazzjoni pubblika dwar il-post magħżul u juri x’inhu magħruf u x’għad irid jiġi kkonfermat.',cta:'Fittex post'},
  SI:{language:'sl',title:'Geologija, tla in tveganja zemljišča v Sloveniji',description:'Raziščite javne podatke o geologiji, tleh, poplavah, plazovih, krasu in podzemnih vodah.',keywords:['geologija parcele','plazovi','poplave','kras','podtalnica'],hazards:['Geologija in tla','Poplave in voda','Plazovi in stabilnost pobočij','Kras in podzemne vode'],intro:'GroundSurf združuje javno dostopne podatke o izbrani lokaciji in loči znane informacije od vprašanj, ki jih je treba še preveriti.',cta:'Poišči lokacijo'},
  BG:{language:'bg',title:'Геология, почва и рискове за имот в България',description:'Разгледайте публична информация за геология, почви, наводнения, свлачища, подземни води и земна основа.',keywords:['геология на имот','свлачища','наводнения','подпочвени води','земна основа'],hazards:['Геология и почви','Наводнения и води','Свлачища и устойчивост на склонове','Подземни води и земна основа'],intro:'GroundSurf събира публичната информация за избраното място и показва какво е известно и какво трябва да бъде потвърдено.',cta:'Търсене на местоположение'},
  NO:{language:'no',title:'Geologi, grunnforhold og naturfare for eiendom i Norge',description:'Utforsk offentlige data om geologi, grunnforhold, skred, flom, marin leire og radon.',keywords:['geologi tomt Norge','skred','flom','marin leire','grunnforhold'],hazards:['Geologi og grunnforhold','Skred og ustabile skråninger','Flom og vann','Marin leire og setninger'],intro:'GroundSurf samler offentlig informasjon om valgt sted og viser hva som er kjent og hva som bør undersøkes nærmere.',cta:'Søk etter et sted'},
  CH:{language:'de',title:'Geologie, Baugrund und Naturgefahren in der Schweiz',description:'Prüfen Sie öffentliche Informationen zu Geologie, Baugrund, Hochwasser, Hanginstabilität und Naturgefahren.',keywords:['Grundstück Geologie Schweiz','Naturgefahren','Hangrutschung','Hochwasser','Baugrund'],hazards:['Geologie und Baugrund','Hochwasser und Gewässer','Hanginstabilität und Massenbewegungen','Gebirgs- und Naturgefahren'],intro:'GroundSurf verbindet öffentliche Informationen zum ausgewählten Standort und zeigt, welche Hinweise vorhanden sind und was noch geprüft werden sollte.',cta:'Standort suchen'},
  GB:{language:'en',title:'Land geology, ground conditions and property hazards in the UK',description:'Explore public evidence about geology, ground conditions, flooding, landslides, subsidence, contamination and ground stability across the UK.',keywords:['land geology UK','subsidence','flood risk','landslides','ground stability'],hazards:['Geology and ground conditions','Flooding and coastal change','Landslides and slope stability','Subsidence and ground stability'],intro:'GroundSurf brings public evidence about a selected location together and separates known evidence from interpretation and further investigation.',cta:'Search a location'},
  IS:{language:'is',title:'Jarðfræði, jarðvegur og náttúruvá fyrir lóð á Íslandi',description:'Skoðaðu opinberar upplýsingar um jarðfræði, jarðveg, skriður, flóð, jarðskjálfta og eldgos.',keywords:['jarðfræði lóðar','jarðvegur','flóð','skriður','jarðskjálftar','eldgos'],hazards:['Jarðfræði og jarðvegur','Skriður og óstöðugar hlíðar','Flóð og vatn','Jarðskjálftar og eldgos'],intro:'GroundSurf safnar saman opinberum upplýsingum um valinn stað og sýnir hvað er vitað og hvað þarf að kanna nánar.',cta:'Leita að staðsetningu'},
  UA:{language:'uk',title:'Геологія, ґрунти та ризики земельної ділянки в Україні',description:'Досліджуйте відкриті дані про геологію, ґрунти, зсуви, підтоплення, підземні води та умови будівництва.',keywords:['геологія ділянки','зсуви','підтоплення','ґрунтові води','просідання'],hazards:['Геологія та ґрунти','Зсуви та стійкість схилів','Підтоплення і води','Просідання та умови фундаменту'],intro:'GroundSurf збирає відкриту інформацію про вибране місце та показує, що відомо і що ще потрібно перевірити.',cta:'Знайти місце'}
};
