steps:
  # Step 1: Build the container image using the multi-stage Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:$COMMIT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:latest'
      - '.'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:$COMMIT_SHA'

  # Step 3: Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'geosurvey-backend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/geosurvey-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
