// Match explicit classifications only: prose mentioning a hazard is not a risk class.
export function riskSeverity(value: string): 'high' | 'moderate' | 'other' {
  const label = value.trim().toLocaleLowerCase();
  if (['high','very high','hoch','sehr hoch','wysokie','wysoki','wysoka','bardzo wysokie','élevé','très élevé','alto','muy alto','korkea','erittäin korkea','hoog','zeer hoog','høj','meget høj','hög','mycket hög','høy','vysoké','veľmi vysoké'].includes(label)) return 'high';
  if (['moderate','medium','mäßig','mittel','umiarkowane','umiarkowany','modéré','moderado','kohtalainen','matig','moderat','middel','måttlig','medelhög','stredné'].includes(label)) return 'moderate';
  return 'other';
}

// Remove repeated complete sentences/paragraphs within a section, never across source records.
// A period must be followed by whitespace, so decimals and URLs stay intact.
export function distinctProse(value?: string, previous = ''): string {
  const parts = (text: string) => text.match(/[^!?]+?[.!?](?=\s|$)|[^!?]+$/gu) || [];
  const key = (text: string) => text.trim().replace(/\s+/g, ' ').toLocaleLowerCase();
  const seen = new Set(parts(previous).map(key));
  return parts(value || '').filter(part => {
    const normalized = key(part);
    if (!normalized || seen.has(normalized)) return false;
    seen.add(normalized);
    return true;
  }).map(part => part.trim()).join(' ');
}

const copies = {
 en: { coverage:'Data coverage', note:'This weighted index describes available evidence, not site quality or risk. It is not a percentage of the plot verified.', flags:'Findings to address before a decision', caution:'A mapped or modelled high-risk classification needs closer assessment. The evidence label describes its source, not whether the site is safe.', findings:'Key findings at a glance', mapped:'Mapped geology', terrain:'Terrain slope', parcel:'Mapped parcel reference', limits:'These results help plan your next checks; they do not establish buildability.', index:'Weighted index' },
 pl: { coverage:'Dostępność danych', note:'Ten ważony wskaźnik opisuje dostępność dowodów, a nie jakość działki ani ryzyko. Nie oznacza procentu zweryfikowanej działki.', flags:'Kwestie do wyjaśnienia przed decyzją', caution:'Wysoka klasa ryzyka z mapy lub modelu wymaga dokładniejszej oceny. Etykieta dowodów opisuje źródło, a nie bezpieczeństwo działki.', findings:'Najważniejsze wyniki w skrócie', mapped:'Geologia według mapy', terrain:'Nachylenie terenu', parcel:'Identyfikator działki na mapie', limits:'Te wyniki pomagają zaplanować dalsze sprawdzenia; nie potwierdzają możliwości zabudowy.', index:'Wskaźnik ważony' },
 de: { coverage:'Datenabdeckung', note:'Dieser gewichtete Index beschreibt verfügbare Nachweise, nicht Grundstücksqualität oder Risiko. Er ist kein Prozentsatz des geprüften Grundstücks.', flags:'Vor einer Entscheidung näher prüfen', caution:'Eine hohe Risikoklasse aus Karten oder Modellen erfordert eine nähere Bewertung. Der Evidenzstatus beschreibt die Quelle, nicht die Sicherheit des Grundstücks.', findings:'Wichtigste Ergebnisse auf einen Blick', mapped:'Kartierte Geologie', terrain:'Geländeneigung', parcel:'Kartierte Flurstücksreferenz', limits:'Diese Ergebnisse helfen bei weiteren Prüfungen; sie bestätigen keine Bebaubarkeit.', index:'Gewichteter Index' },
 nl: { coverage:'Datadekking', note:'Deze gewogen index beschrijft het beschikbare bewijs, niet de kwaliteit of het risico van het perceel. Het is geen percentage van het perceel dat is geverifieerd.', flags:'Punten om vóór een beslissing uit te zoeken', caution:'Een hoge risicoklasse uit kaarten of modellen vraagt om nadere beoordeling. De bewijsstatus beschrijft de bron, niet of het perceel veilig is.', findings:'Belangrijkste bevindingen in één oogopslag', mapped:'Gekarteerde geologie', terrain:'Terreinhelling', parcel:'Gekarteerde perceelreferentie', limits:'Deze resultaten helpen uw volgende controles te plannen; ze stellen niet vast dat bebouwing is toegestaan of haalbaar is.', index:'Gewogen index' },
 fi: { coverage:'Tietojen kattavuus', note:'Painotettu indeksi kuvaa saatavilla olevaa näyttöä, ei tontin laatua tai riskiä. Se ei ole tarkistetun tontin prosenttiosuus.', flags:'Asiat, jotka on selvitettävä ennen päätöstä', caution:'Kartasta tai mallista saatu korkea riskiluokka vaatii tarkempaa arviointia. Näytön tila kuvaa lähdettä, ei tontin turvallisuutta.', findings:'Tärkeimmät havainnot yhdellä silmäyksellä', mapped:'Kartoitettu geologia', terrain:'Maaston kaltevuus', parcel:'Kartoitettu kiinteistöviite', limits:'Tulokset auttavat suunnittelemaan seuraavat tarkistukset; ne eivät vahvista rakennusoikeutta tai rakentamiskelpoisuutta.', index:'Painotettu indeksi' },
 cs: { coverage:'Datové pokrytí', note:'Tento vážený ukazatel popisuje dostupné podklady, nikoli kvalitu či rizikovost pozemku. Nejde o procento ověřené plochy.', flags:'Otázky k ověření před rozhodnutím', caution:'Vysoká riziková třída z mapy nebo modelu vyžaduje podrobnější posouzení. Stav důkazu popisuje zdroj, nikoli bezpečnost pozemku.', findings:'Nejdůležitější zjištění na první pohled', mapped:'Mapovaná geologie', terrain:'Sklon terénu', parcel:'Mapovaná reference parcely', limits:'Výsledky pomáhají naplánovat další kontroly; nepotvrzují stavební využitelnost.', index:'Vážený ukazatel' },
 fr: { coverage:'Couverture des données', note:'Cet indice pondéré décrit les preuves disponibles, pas la qualité du terrain ni le risque. Ce n’est pas un pourcentage du terrain vérifié.', flags:'Points à clarifier avant une décision', caution:'Une classe de risque élevée issue d’une carte ou d’un modèle nécessite une évaluation plus approfondie. Le statut des preuves décrit la source, pas la sécurité du terrain.', findings:'Principaux constats en un coup d’œil', mapped:'Géologie cartographiée', terrain:'Pente du terrain', parcel:'Référence cadastrale cartographiée', limits:'Ces résultats aident à organiser les vérifications suivantes ; ils ne confirment pas la constructibilité.', index:'Indice pondéré' },
 es: { coverage:'Cobertura de datos', note:'Este índice ponderado describe la evidencia disponible, no la calidad ni el riesgo de la parcela. No es un porcentaje de la parcela verificada.', flags:'Aspectos que conviene aclarar antes de decidir', caution:'Una clase de riesgo alta procedente de mapas o modelos requiere una evaluación más detallada. El estado de la evidencia describe la fuente, no si la parcela es segura.', findings:'Resultados clave de un vistazo', mapped:'Geología cartografiada', terrain:'Pendiente del terreno', parcel:'Referencia catastral cartografiada', limits:'Estos resultados ayudan a planificar las siguientes comprobaciones; no confirman la edificabilidad.', index:'Índice ponderado' },
 sv: { coverage:'Datatäckning', note:'Detta viktade index beskriver vilket underlag som finns tillgängligt, inte tomtens kvalitet eller risk. Det är inte en procentandel av tomten som har verifierats.', flags:'Frågor att reda ut före beslut', caution:'En hög riskklass från karta eller modell kräver närmare bedömning. Evidensstatus beskriver källan, inte om tomten är säker.', findings:'Viktigaste resultaten i korthet', mapped:'Kartlagd geologi', terrain:'Terränglutning', parcel:'Kartlagd fastighetsreferens', limits:'Resultaten hjälper dig att planera nästa kontroller; de fastställer inte att tomten är byggbar.', index:'Viktat index' },
 no: { coverage:'Dokumentasjonsdekning', note:'Denne vektede indikatoren beskriver tilgjengelig dokumentasjon, ikke tomtens kvalitet eller risiko. Den er ikke en prosentandel av tomten som er verifisert.', flags:'Forhold som bør avklares før en beslutning', caution:'En høy risikoklasse fra kart eller modell krever nærmere vurdering. Dokumentasjonsstatus beskriver kilden, ikke om tomten er trygg.', findings:'Viktigste funn i korte trekk', mapped:'Kartlagt geologi', terrain:'Terrenghelning', parcel:'Kartlagt matrikkelreferanse', limits:'Resultatene hjelper deg å planlegge videre kontroller; de fastslår ikke at tomten er byggbar.', index:'Vektet indeks' },
 sk: { coverage:'Pokrytie dôkazmi', note:'Tento vážený ukazovateľ opisuje dostupné dôkazy, nie kvalitu alebo rizikovosť pozemku. Nejde o percento overenej parcely.', flags:'Otázky, ktoré treba vyriešiť pred rozhodnutím', caution:'Vysoká riziková trieda z mapy alebo modelu si vyžaduje podrobnejšie posúdenie. Stav dôkazov opisuje zdroj, nie bezpečnosť pozemku.', findings:'Najdôležitejšie zistenia v skratke', mapped:'Mapovaná geológia', terrain:'Sklon terénu', parcel:'Mapovaná referencia parcely', limits:'Výsledky pomáhajú naplánovať ďalšie kontroly; nepotvrdzujú stavebnú využiteľnosť.', index:'Vážený index' },
 da: { coverage:'Datadækning', note:'Dette vægtede indeks beskriver det tilgængelige evidensgrundlag, ikke grundens kvalitet eller risiko. Det er ikke en procentdel af grunden, der er verificeret.', flags:'Forhold der bør afklares før en beslutning', caution:'En høj risikoklasse fra kort eller modeller kræver nærmere vurdering. Evidensstatus beskriver kilden, ikke om grunden er sikker.', findings:'Vigtigste resultater på et øjeblik', mapped:'Kortlagt geologi', terrain:'Terrænhældning', parcel:'Kortlagt matrikelreference', limits:'Resultaterne hjælper med at planlægge de næste kontroller; de dokumenterer ikke byggeret eller byggemulighed.', index:'Vægtet indeks' }
};
const coverageTranslations: Record<string, {coverage:string; note:string; index:string}> = {
 fr: {coverage:'Couverture des données', note:'Cet indice pondéré décrit les preuves disponibles, pas la qualité du terrain ni le risque. Ce n’est pas un pourcentage du terrain vérifié.', index:'Indice pondéré'},
 es: {coverage:'Cobertura de datos', note:'Este índice ponderado describe la evidencia disponible, no la calidad del terreno ni el riesgo. No es un porcentaje del terreno verificado.', index:'Índice ponderado'},
 fi: {coverage:'Tietojen kattavuus', note:'Painotettu indeksi kuvaa saatavilla olevaa näyttöä, ei tontin laatua tai riskiä. Se ei ole tarkistetun tontin prosenttiosuus.', index:'Painotettu indeksi'},
 nl: {coverage:'Datadekking', note:'Deze gewogen index beschrijft beschikbare informatie, niet de kwaliteit of het risico van het perceel. Het is geen percentage van het gecontroleerde perceel.', index:'Gewogen index'}
};
export const coverageCopy = (language:string) => coverageTranslations[language.toLowerCase().slice(0,2)] || findingsCopy(language);
export const findingsCopy = (language: string) => copies[language.toLowerCase().slice(0,2) as keyof typeof copies] || copies.en;

type BuyerInput = {
 slope?: number | null;
 risks: {category:string; level:string; evidence_level?:string}[];
 planningConfirmed:boolean;
 floodConfirmed:boolean;
};
const buyerCopies = {
 en: {suitabilityNote:'A preliminary view of site conditions, not confirmation that development is permitted or feasible.', positive:'Suitability for development', concerns:'Potential hazards', checks:'What still needs checking', flat:'The terrain has a gentle mapped slope ({slope}°). This may simplify layout, though foundations and drainage still need checking.', low:'{category}: the reported classification is {level}. This is an encouraging screening result, not a site guarantee.', risk:'{category}: {level}. Ask a qualified specialist how this could affect your proposed use and costs.', noPositive:'The available evidence is not enough to assess development suitability.', noConcern:'No explicit moderate or high hazard classification was returned. Incomplete coverage means other risks may remain.', planning:'Confirm that your intended use is permitted with the local planning authority.', flood:'Check the official flood assessment before proceeding with your plans.', site:'Confirm boundaries, access and ground conditions for your intended use.' },
 pl: {suitabilityNote:'Wstępny obraz warunków działki, a nie potwierdzenie, że zabudowa jest dozwolona lub wykonalna.', positive:'Przydatność do zabudowy', concerns:'Potencjalne zagrożenia', checks:'Co jeszcze trzeba sprawdzić', flat:'Teren ma niewielkie nachylenie według modelu ({slope}°). Może to ułatwić rozplanowanie zabudowy, ale fundamenty i odwodnienie nadal wymagają sprawdzenia.', low:'{category}: zgłoszona klasa to {level}. To zachęcający wynik wstępnego sprawdzenia, a nie gwarancja bezpieczeństwa działki.', risk:'{category}: {level}. Zapytaj specjalistę, jak może to wpłynąć na planowane wykorzystanie i koszty.', noPositive:'Dostępne dane nie wystarczają jeszcze do oceny przydatności do zabudowy.', noConcern:'Nie zwrócono jednoznacznej umiarkowanej ani wysokiej klasy zagrożenia. Niepełne dane mogą pozostawiać inne ryzyka nierozpoznane.', planning:'Potwierdź we właściwym urzędzie, czy planowane wykorzystanie działki jest dozwolone.', flood:'Przed realizacją planów sprawdź oficjalną ocenę zagrożenia powodziowego.', site:'Potwierdź granice, dostęp i warunki gruntowe dla planowanego wykorzystania.' },
 de: {suitabilityNote:'Eine erste Einschätzung der Standortbedingungen, keine Bestätigung, dass eine Bebauung zulässig oder machbar ist.', positive:'Eignung für eine Bebauung', concerns:'Mögliche Gefahren', checks:'Was noch zu prüfen ist', flat:'Das Gelände weist laut Modell eine geringe Neigung auf ({slope}°). Das kann die Anordnung der Bebauung erleichtern; Gründung und Entwässerung bleiben zu prüfen.', low:'{category}: gemeldete Klasse {level}. Ein ermutigendes erstes Ergebnis, keine Sicherheitsgarantie für das Grundstück.', risk:'{category}: {level}. Lassen Sie fachlich prüfen, wie dies Ihre geplante Nutzung und Kosten beeinflussen könnte.', noPositive:'Die verfügbaren Daten reichen noch nicht aus, um die Eignung für eine Bebauung zu beurteilen.', noConcern:'Es wurde keine ausdrückliche mittlere oder hohe Gefahrenklasse zurückgegeben. Bei unvollständigen Daten können weitere Risiken offenbleiben.', planning:'Bestätigen Sie mit der Planungsbehörde, dass Ihre geplante Nutzung zulässig ist.', flood:'Prüfen Sie vor der Umsetzung Ihrer Pläne die amtliche Hochwasserbewertung.', site:'Bestätigen Sie Grenzen, Zugang und Baugrund für Ihre geplante Nutzung.' },
 nl: {suitabilityNote:'Een voorlopige indruk van de locatieomstandigheden, geen bevestiging dat ontwikkeling is toegestaan of haalbaar is.', positive:'Wat in het voordeel van het perceel kan werken', concerns:'Wat uw plannen kan beïnvloeden', checks:'Wat u vóór aankoop moet controleren', flat:'Het terrein heeft volgens het model een geringe helling ({slope}°). Dat kan de indeling vergemakkelijken, maar fundering en afwatering moeten nog worden onderzocht.', low:'{category}: de gemelde klasse is {level}. Dit is een gunstig screeningssignaal, geen garantie voor het perceel.', risk:'{category}: {level}. Laat een deskundige beoordelen hoe dit uw beoogde gebruik en kosten kan beïnvloeden.', noPositive:'Het beschikbare bewijs is nog onvoldoende om de geschiktheid voor ontwikkeling te beoordelen.', noConcern:'Er is geen expliciete matige of hoge risicoklasse teruggegeven. Door onvolledige dekking kunnen andere risico’s nog onbekend zijn.', planning:'Bevestig bij de bevoegde overheid dat uw beoogde gebruik en ontwikkeling zijn toegestaan.', flood:'Controleer de officiële overstromingsbeoordeling voordat u verdergaat.', site:'Bevestig grenzen, toegang en bodemomstandigheden voor het beoogde gebruik.' },
 fi: {suitabilityNote:'Alustava kuva tontin olosuhteista — ei vahvistus siitä, että rakentaminen on sallittua tai toteuttamiskelpoista.', positive:'Tontin kannalta myönteiset tekijät', concerns:'Suunnitelmiin mahdollisesti vaikuttavat tekijät', checks:'Tarkista nämä ennen ostopäätöstä', flat:'Maastomalli osoittaa loivan kaltevuuden ({slope}°). Tämä voi helpottaa suunnittelua, mutta perustamis- ja kuivatusolosuhteet on silti tutkittava.', low:'{category}: ilmoitettu luokka on {level}. Tämä on myönteinen seulontatulos, ei tonttikohtainen takuu.', risk:'{category}: {level}. Pyydä asiantuntijaa arvioimaan, miten tämä voi vaikuttaa suunniteltuun käyttöön ja kustannuksiin.', noPositive:'Saatavilla oleva näyttö ei vielä riitä rakentamiskelpoisuuden arviointiin.', noConcern:'Selvää kohtalaista tai korkeaa riskiluokkaa ei palautettu. Puutteellinen tietokattavuus voi jättää muita riskejä avoimiksi.', planning:'Vahvista kunnalta, että suunniteltu käyttö ja rakentaminen ovat sallittuja.', flood:'Tarkista virallinen tulvariski ennen suunnitelmien edistämistä.', site:'Vahvista rajat, kulkuyhteydet ja maaperäolosuhteet suunniteltua käyttöä varten.' },
 cs: {suitabilityNote:'Předběžný pohled na podmínky pozemku — nikoli potvrzení, že je výstavba povolena nebo proveditelná.', positive:'Co může být ve prospěch pozemku', concerns:'Co může ovlivnit vaše plány', checks:'Co ověřit před koupí', flat:'Model terénu ukazuje malý sklon ({slope}°). To může usnadnit návrh, ale založení a odvodnění je stále nutné prověřit.', low:'{category}: uvedená třída je {level}. Jde o příznivý screeningový signál, nikoli záruku pro konkrétní pozemek.', risk:'{category}: {level}. Nechte odborně posoudit, jak to může ovlivnit zamýšlené využití a náklady.', noPositive:'Dostupné podklady zatím nestačí k posouzení vhodnosti pozemku pro výstavbu.', noConcern:'Nebyla vrácena jednoznačná střední ani vysoká riziková třída. Neúplné pokrytí může znamenat další nevyjasněná rizika.', planning:'Ověřte u příslušného úřadu, že zamýšlené využití a výstavba jsou přípustné.', flood:'Před dalším postupem ověřte oficiální povodňové podklady.', site:'Ověřte hranice, přístup a základové podmínky pro zamýšlené využití.' },
 fr: {suitabilityNote:'Une première lecture des conditions du terrain — pas une confirmation que le projet est autorisé ou réalisable.', positive:'Éléments pouvant être favorables au terrain', concerns:'Éléments pouvant affecter votre projet', checks:'À vérifier avant l’achat', flat:'Le modèle de terrain indique une faible pente ({slope}°). Cela peut faciliter l’implantation, mais les fondations et le drainage doivent encore être vérifiés.', low:'{category} : la classe indiquée est {level}. C’est un signal de présélection favorable, pas une garantie pour le terrain.', risk:'{category} : {level}. Demandez à un spécialiste d’évaluer l’incidence possible sur votre usage prévu et les coûts.', noPositive:'Les données disponibles ne suffisent pas encore pour juger l’aptitude du terrain à la construction.', noConcern:'Aucune classe de risque modérée ou élevée explicite n’a été renvoyée. Une couverture incomplète peut laisser d’autres risques non résolus.', planning:'Confirmez auprès de l’autorité locale que l’usage et le projet envisagés sont autorisés.', flood:'Vérifiez l’évaluation officielle du risque d’inondation avant de poursuivre.', site:'Confirmez les limites, l’accès et les conditions du sol pour l’usage prévu.' },
 es: {suitabilityNote:'Una primera visión de las condiciones de la parcela, no una confirmación de que el desarrollo esté permitido o sea viable.', positive:'Aspectos que pueden favorecer la parcela', concerns:'Aspectos que pueden afectar a sus planes', checks:'Qué comprobar antes de comprar', flat:'El modelo del terreno muestra una pendiente suave ({slope}°). Esto puede facilitar la implantación, aunque la cimentación y el drenaje aún deben comprobarse.', low:'{category}: la clase indicada es {level}. Es una señal preliminar favorable, no una garantía para la parcela.', risk:'{category}: {level}. Pida a un especialista que valore cómo podría afectar al uso previsto y a los costes.', noPositive:'La evidencia disponible todavía no basta para evaluar la aptitud de la parcela para construir.', noConcern:'No se devolvió una clase de riesgo moderada o alta explícita. La cobertura incompleta puede dejar otros riesgos sin resolver.', planning:'Confirme con la autoridad local que el uso y el desarrollo previstos están permitidos.', flood:'Compruebe la evaluación oficial de inundación antes de seguir adelante.', site:'Confirme los límites, el acceso y las condiciones del terreno para el uso previsto.' },
 sv: {suitabilityNote:'En preliminär bild av tomtens förutsättningar — inte en bekräftelse på att byggnation är tillåten eller genomförbar.', positive:'Förhållanden som kan tala för tomten', concerns:'Förhållanden som kan påverka dina planer', checks:'Det här bör du kontrollera före köp', flat:'Terrängmodellen visar en låg lutning ({slope}°). Det kan underlätta dispositionen, men grundläggning och dränering behöver fortfarande undersökas.', low:'{category}: angiven klass är {level}. Det är en positiv screeningsignal, inte en garanti för förhållandena på tomten.', risk:'{category}: {level}. Låt en kvalificerad specialist bedöma hur detta kan påverka planerad användning och kostnader.', noPositive:'Det tillgängliga underlaget räcker ännu inte för att bedöma tomtens lämplighet för byggnation.', noConcern:'Ingen tydlig måttlig eller hög riskklass returnerades. Ofullständig datatäckning innebär att andra risker fortfarande kan vara oklara.', planning:'Bekräfta hos kommunen att planerad användning och byggnation är tillåten.', flood:'Kontrollera den officiella översvämningsbedömningen innan du går vidare.', site:'Bekräfta fastighetsgränser, tillfart och markförhållanden för den planerade användningen.' },
 no: {suitabilityNote:'En foreløpig vurdering av tomteforholdene — ikke en bekreftelse på at utbygging er tillatt eller gjennomførbar.', positive:'Forhold som kan tale for tomten', concerns:'Forhold som kan påvirke planene dine', checks:'Dette bør du kontrollere før kjøp', flat:'Terrengmodellen viser en lav helning ({slope}°). Det kan forenkle disponeringen, men fundamentering og drenering må fortsatt undersøkes.', low:'{category}: oppgitt klasse er {level}. Det er et positivt screeningssignal, ikke en garanti for forholdene på tomten.', risk:'{category}: {level}. Be en kvalifisert fagperson vurdere hvordan dette kan påvirke planlagt bruk og kostnader.', noPositive:'Tilgjengelig dokumentasjon er ennå ikke tilstrekkelig til å vurdere tomtens egnethet for utbygging.', noConcern:'Ingen tydelig moderat eller høy risikoklasse ble returnert. Ufullstendig dekning betyr at andre risikoer fortsatt kan være uavklarte.', planning:'Bekreft hos kommunen at planlagt bruk og utbygging er tillatt.', flood:'Kontroller den offisielle flomvurderingen før du går videre.', site:'Bekreft eiendomsgrenser, adkomst og grunnforhold for planlagt bruk.' },
 sk: {suitabilityNote:'Predbežný pohľad na podmienky lokality — nie potvrdenie, že výstavba je povolená alebo uskutočniteľná.', positive:'Čo môže hovoriť v prospech pozemku', concerns:'Čo môže ovplyvniť vaše plány', checks:'Čo treba overiť pred kúpou', flat:'Model terénu ukazuje mierny sklon ({slope}°). To môže uľahčiť dispozičné riešenie, ale založenie a odvodnenie treba stále preveriť.', low:'{category}: uvedená trieda je {level}. Ide o priaznivý skríningový signál, nie záruku podmienok na pozemku.', risk:'{category}: {level}. Nechajte odborníka posúdiť, ako to môže ovplyvniť plánované využitie a náklady.', noPositive:'Dostupné dôkazy zatiaľ nestačia na posúdenie vhodnosti pozemku na výstavbu.', noConcern:'Nebola vrátená jednoznačná stredná ani vysoká riziková trieda. Neúplné pokrytie môže ponechať ďalšie riziká neobjasnené.', planning:'Overte na príslušnom úrade, či je plánované využitie a výstavba povolená.', flood:'Pred ďalším postupom skontrolujte oficiálne povodňové podklady.', site:'Overte hranice, prístup a základové podmienky pre plánované využitie.' },
 da: {suitabilityNote:'En foreløbig vurdering af grundforholdene — ikke en bekræftelse af, at byggeri er tilladt eller gennemførligt.', positive:'Forhold der kan tale for grunden', concerns:'Forhold der kan påvirke dine planer', checks:'Det bør du kontrollere før køb', flat:'Terrænmodellen viser en lav hældning ({slope}°). Det kan være gunstigt for disponering, men fundering og afvanding skal stadig undersøges.', low:'{category}: den angivne klasse er {level}. Det er et positivt screeningssignal, ikke en garanti for forholdene på grunden.', risk:'{category}: {level}. Få en fagperson til at vurdere, hvordan dette kan påvirke den planlagte anvendelse og omkostningerne.', noPositive:'Det tilgængelige evidensgrundlag er endnu ikke tilstrækkeligt til at vurdere grundens egnethed til byggeri.', noConcern:'Der blev ikke returneret en entydig moderat eller høj risikoklasse. Ufuldstændig datadækning betyder, at andre risici stadig kan være uafklarede.', planning:'Bekræft hos kommunen, at din planlagte anvendelse og bebyggelse er tilladt.', flood:'Kontrollér den officielle oversvømmelsesvurdering, før du går videre med dine planer.', site:'Bekræft matrikelgrænser, adgang og grundforhold for den planlagte anvendelse.' }
};
export function buyerSummary(input:BuyerInput, language:string) {
 const copy=buyerCopies[language.toLowerCase().slice(0,2) as keyof typeof buyerCopies] || buyerCopies.en;
 const positives:string[]=[];
 if (typeof input.slope==='number' && Number.isFinite(input.slope) && input.slope>=0 && input.slope<=5) positives.push(copy.flat.replace('{slope}',String(input.slope)));
 const lowLabels=['low','negligible','gering','niedrig','vernachlässigbar','niskie','niski','znikome','lav','ubetydelig','laag','verwaarloosbaar','matala','merkityksetön','nízké','zanedbatelné','låg','försumbar','nízke','zanedbateľné'];
 for (const risk of input.risks) {
   if (['VERIFIED','MODELLED'].includes(risk.evidence_level || '') && lowLabels.includes(risk.level.trim().toLowerCase())) positives.push(copy.low.replace('{category}',risk.category).replace('{level}',risk.level));
 }
 const concerns=input.risks.filter(r=>riskSeverity(r.level)!=='other').sort((a,b)=>(riskSeverity(a.level)==='high'?0:1)-(riskSeverity(b.level)==='high'?0:1)).map(r=>copy.risk.replace('{category}',r.category).replace('{level}',r.level));
 const checks=[...(!input.planningConfirmed?[copy.planning]:[]),...(!input.floodConfirmed?[copy.flood]:[]),copy.site];
 return {copy, positives:positives.slice(0,2), concerns:concerns.slice(0,2), checks};
}

export function decisionIntroCopy(language:string) {
  const code=language.toLowerCase().slice(0,2);
  const copies: Record<string,{verdict:string; complete:string; first:string; evidence:string; limited:string; next:string; clear:string; disclaimer:string; nextTitle:string; nextLead:string}> = {
    en:{verdict:'A useful first check — key questions remain',complete:'Land evidence, brought together',first:'LandSurf brings the available land evidence for this site into one place.',evidence:'The report includes mapped parcel or geological evidence.',limited:'Only limited source-verified evidence was available for this site.',next:'Before a decision, confirm planning and flood information in official records and check conditions on site.',clear:'Planning and flood findings appear below; confirm them before a decision.',disclaimer:'This is a first check, not a legal certificate.',nextTitle:'Your next checks',nextLead:'Start with these questions before making a commitment.'},
    de:{verdict:'Erster Überblick — wichtige Fragen noch prüfen',complete:'Grundstücksdaten gebündelt',first:'LandSurf bündelt die verfügbaren Daten zu diesem Standort an einem Ort.',evidence:'Der Bericht enthält kartierte Flurstücks- oder Geologiedaten.',limited:'Für diesen Standort liegen nur begrenzte bestätigte Daten vor.',next:'Prüfen Sie vor einer Entscheidung amtliche Planungs- und Hochwasserunterlagen sowie die Verhältnisse vor Ort.',clear:'Planungs- und Hochwasserdaten stehen unten; bestätigen Sie sie vor einer Entscheidung.',disclaimer:'Dies ist eine erste Prüfung, keine amtliche Bescheinigung.',nextTitle:'Ihre nächsten Schritte',nextLead:'Klären Sie diese Fragen vor Ihrer Entscheidung.'},
    pl:{verdict:'Pierwszy obraz działki — ważne kwestie wymagają potwierdzenia',complete:'Dane o działce zebrane w jednym miejscu',first:'LandSurf zbiera dostępne dane o tej lokalizacji w jednym miejscu.',evidence:'Raport zawiera dane o działce lub geologii z mapowanych źródeł.',limited:'Dla tej lokalizacji dostępne są tylko ograniczone dane potwierdzone w źródłach.',next:'Przed podjęciem decyzji sprawdź oficjalne dokumenty planistyczne i powodziowe oraz warunki na miejscu.',clear:'Dane dotyczące planowania i powodzi znajdziesz poniżej; potwierdź je przed podjęciem decyzji.',disclaimer:'To wstępne sprawdzenie, a nie urzędowe zaświadczenie.',nextTitle:'Twoje kolejne kroki',nextLead:'Zacznij od tych kwestii przed podjęciem decyzji.'},
    nl:{verdict:'Een nuttige eerste controle — belangrijke vragen blijven open',complete:'Perceelinformatie samengebracht',first:'LandSurf brengt de beschikbare informatie over dit perceel op één plek samen.',evidence:'Het rapport bevat gekarteerde perceel- of geologische informatie.',limited:'Voor deze locatie was slechts beperkt bron-geverifieerd bewijs beschikbaar.',next:'Controleer vóór een beslissing de officiële planologische en overstromingsinformatie en de omstandigheden ter plaatse.',clear:'Planologische en overstromingsbevindingen staan hieronder; bevestig ze vóór een beslissing.',disclaimer:'Dit is een eerste controle, geen juridisch of officieel certificaat.',nextTitle:'Uw volgende controles',nextLead:'Begin met deze vragen voordat u zich vastlegt.'},
    fi:{verdict:'Hyödyllinen ensitarkistus — keskeisiä kysymyksiä on vielä avoinna',complete:'Tonttitiedot koottuna yhteen',first:'LandSurf kokoaa saatavilla olevan tonttia koskevan näytön yhteen paikkaan.',evidence:'Raportti sisältää kartoitettua kiinteistö- tai geologista näyttöä.',limited:'Tälle kohteelle oli saatavilla vain rajallisesti lähteistä vahvistettua näyttöä.',next:'Vahvista ennen päätöstä viralliset kaavoitus- ja tulvatiedot sekä kohteen olosuhteet paikan päällä.',clear:'Kaavoitus- ja tulvahavainnot esitetään alla; vahvista ne ennen päätöstä.',disclaimer:'Tämä on alustava tarkistus, ei virallinen todistus.',nextTitle:'Seuraavat tarkistukset',nextLead:'Aloita näistä kysymyksistä ennen sitovan päätöksen tekemistä.'},
    sv:{verdict:'En användbar första kontroll — viktiga frågor återstår',complete:'Tomtunderlaget samlat på ett ställe',first:'LandSurf samlar det tillgängliga underlaget för den här tomten på ett ställe.',evidence:'Rapporten innehåller kartlagda fastighets- eller geologiska uppgifter.',limited:'Endast ett begränsat källverifierat underlag fanns tillgängligt för den här tomten.',next:'Före ett beslut bör du kontrollera officiella plan- och översvämningsuppgifter samt förhållandena på plats.',clear:'Plan- och översvämningsresultat visas nedan; bekräfta dem före ett beslut.',disclaimer:'Detta är en första kontroll, inte ett myndighetsintyg.',nextTitle:'Dina nästa kontroller',nextLead:'Börja med de här frågorna innan du binder dig till tomten.'},
    no:{verdict:'En nyttig første kontroll — viktige spørsmål gjenstår',complete:'Tomtedokumentasjon samlet på ett sted',first:'LandSurf samler den tilgjengelige dokumentasjonen for denne tomten på ett sted.',evidence:'Rapporten inneholder kartlagt eiendoms- eller geologisk dokumentasjon.',limited:'Bare begrenset kildeverifisert dokumentasjon var tilgjengelig for denne tomten.',next:'Før en beslutning bør du kontrollere offisiell arealplan- og flominformasjon samt forholdene på stedet.',clear:'Plan- og flomfunn vises nedenfor; bekreft dem før en beslutning.',disclaimer:'Dette er en første kontroll, ikke en offentlig attest.',nextTitle:'Dine neste kontroller',nextLead:'Start med disse spørsmålene før du binder deg til tomten.'},
    sk:{verdict:'Užitočná prvá kontrola — kľúčové otázky zostávajú otvorené',complete:'Podklady o pozemku na jednom mieste',first:'LandSurf zhromažďuje dostupné podklady o tejto lokalite na jednom mieste.',evidence:'Report obsahuje mapované katastrálne alebo geologické podklady.',limited:'Pre túto lokalitu bolo dostupné iba obmedzené množstvo zdrojovo overených podkladov.',next:'Pred rozhodnutím overte oficiálne územnoplánovacie a povodňové podklady a podmienky priamo na mieste.',clear:'Výsledky plánovania a povodní sú uvedené nižšie; pred rozhodnutím ich potvrďte.',disclaimer:'Ide o úvodnú kontrolu, nie o úradné potvrdenie.',nextTitle:'Vaše ďalšie kontroly',nextLead:'Začnite týmito otázkami pred tým, než sa k pozemku zaviažete.'},
    da:{verdict:'En nyttig første vurdering — vigtige spørgsmål er stadig åbne',complete:'Grundoplysninger samlet ét sted',first:'LandSurf samler de tilgængelige oplysninger om denne grund ét sted.',evidence:'Rapporten indeholder kortlagte matrikel- eller geologiske oplysninger.',limited:'Der var kun begrænset kildeverificeret evidens tilgængelig for denne grund.',next:'Før en beslutning bør du kontrollere officielle plan- og oversvømmelsesoplysninger samt forholdene på selve grunden.',clear:'Plan- og oversvømmelsesforhold fremgår nedenfor; bekræft dem før en beslutning.',disclaimer:'Dette er en indledende screening, ikke en myndighedsattest.',nextTitle:'Dine næste kontroller',nextLead:'Start med disse spørgsmål, før du binder dig til grunden.'},
    cs:{verdict:'Užitečná první kontrola — klíčové otázky zůstávají otevřené',complete:'Podklady o pozemku na jednom místě',first:'LandSurf soustřeďuje dostupné podklady o tomto pozemku na jednom místě.',evidence:'Zpráva obsahuje mapované katastrální nebo geologické podklady.',limited:'Pro tuto lokalitu bylo k dispozici jen omezené množství zdrojově ověřených podkladů.',next:'Před rozhodnutím ověřte v oficiálních zdrojích územní plánování a povodňové informace a prověřte podmínky přímo na místě.',clear:'Výsledky k plánování a povodním jsou uvedeny níže; před rozhodnutím je potvrďte.',disclaimer:'Jde o první kontrolu, nikoli o úřední osvědčení.',nextTitle:'Co ověřit jako další',nextLead:'Začněte těmito otázkami, než se k pozemku závazně rozhodnete.'},
    fr:{verdict:'Une première vérification utile — des questions clés restent ouvertes',complete:'Les données foncières réunies',first:'LandSurf rassemble en un seul endroit les données disponibles sur ce terrain.',evidence:'Le rapport contient des données cadastrales ou géologiques cartographiées.',limited:'Seules des données limitées et vérifiées à la source étaient disponibles pour ce site.',next:'Avant toute décision, confirmez l’urbanisme et le risque d’inondation dans les sources officielles et vérifiez les conditions sur place.',clear:'Les résultats d’urbanisme et d’inondation figurent ci-dessous ; confirmez-les avant toute décision.',disclaimer:'Il s’agit d’une première vérification, pas d’un certificat officiel.',nextTitle:'Vos prochaines vérifications',nextLead:'Commencez par ces questions avant de vous engager.'},
    es:{verdict:'Una primera comprobación útil — quedan cuestiones clave por resolver',complete:'La información de la parcela, reunida',first:'LandSurf reúne en un solo lugar la información disponible sobre esta parcela.',evidence:'El informe incluye información catastral o geológica cartografiada.',limited:'Para este emplazamiento solo había evidencia limitada verificada en origen.',next:'Antes de decidir, confirme la información urbanística y de inundación en fuentes oficiales y compruebe las condiciones sobre el terreno.',clear:'Los resultados de planeamiento e inundación figuran más abajo; confírmelos antes de decidir.',disclaimer:'Es una comprobación inicial, no un certificado oficial.',nextTitle:'Sus próximas comprobaciones',nextLead:'Empiece por estas cuestiones antes de comprometerse.'}
  };
  return copies[code] || copies.en;
}

[executed on device: toma (e8359509-e325-4515-b2ff-2da47ff811ad)]