import assert from 'node:assert/strict'; import test from 'node:test';
import { clearOperationalMetadata, getOperationalMetadata, resolveSource } from './resolver';
import { candidateReplacement } from './discovery';
import { schemaFingerprint } from './schemaValidator';
import { LogicalSourceId, SourceEndpoint } from './sourceTypes';

const id: LogicalSourceId = 'BGS_DETAILED_GEOLOGY';
const endpoint = (name:string, priority:number, tier:1|2=1, approval:'APPROVED'|'CANDIDATE'='APPROVED'):SourceEndpoint => ({ id:name, logicalSourceId:id, provider:'BGS', country:'GB', coverage:'test', type:'ARCGIS_REST', url:`https://test/${name}`, priority, evidenceTier:tier, compatibilityGroup:'test', expectedCapabilities:['query'], expectedLayers:[4], requiredFieldGroups:[['LEX_D'],['RCS_D']], provenance:'test', approval });
const registry = (items:SourceEndpoint[]) => new Map([[id,items]]);
const healthy = (fields=['LEX_D','RCS_D']) => ({ connectivity:true, httpStatus:200, serviceAvailable:true, observedLayers:[4], observedFields:fields.map(name=>({name,type:'esriFieldTypeString'})), capabilities:['query'] });

test('resolver accepts a healthy primary only after service and schema validation', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async()=>healthy(),{registry:registry([endpoint('primary',1)])}); assert.equal(result.status,'HEALTHY'); assert.equal(result.endpoint?.id,'primary'); assert.ok(result.provenance?.schemaFingerprint); });
test('resolver uses an approved equivalent fallback when primary is unavailable', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false,httpStatus:503}:healthy(),{registry:registry([endpoint('primary',1),endpoint('equivalent',2)])}); assert.equal(result.status,'FALLBACK_ACTIVE'); assert.equal(result.endpoint?.id,'equivalent'); });
test('lower-tier fallback retains its lower evidence tier', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false}:healthy(),{registry:registry([endpoint('primary',1),endpoint('regional',2,2)])}); assert.equal(result.provenance?.evidenceTier,2); });
test('HTTP 200 with missing required schema is SCHEMA_CHANGED', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async()=>healthy(['LEX_D']),{registry:registry([endpoint('primary',1)])}); assert.equal(result.status,'SCHEMA_CHANGED'); assert.equal(result.endpoint,null); });
test('rate limiting and all unavailable routes stay machine readable', async()=>{ clearOperationalMetadata(); const rate=await resolveSource(id,async()=>({...healthy(),httpStatus:429}),{registry:registry([endpoint('primary',1)])}); assert.equal(rate.status,'RATE_LIMITED'); clearOperationalMetadata(); const down=await resolveSource(id,async()=>({...healthy(),connectivity:false,httpStatus:503}),{registry:registry([endpoint('primary',1)])}); assert.equal(down.status,'UNAVAILABLE'); });
test('fingerprint changes are detected for a previously cached endpoint', async()=>{ clearOperationalMetadata(); const reg=registry([endpoint('primary',1)]); await resolveSource(id,async()=>healthy(),{registry:reg,ttlMs:0}); const changed=await resolveSource(id,async()=>({...healthy(),observedFields:[{name:'LEX_D',type:'changed'},{name:'RCS_D',type:'string'}]}),{registry:reg,ttlMs:0}); assert.equal(changed.status,'SCHEMA_CHANGED'); });
test('cached healthy endpoint is tried first within TTL', async()=>{ clearOperationalMetadata(); const calls:string[]=[]; const reg=registry([endpoint('primary',1),endpoint('fallback',2)]); await resolveSource(id,async ep=>{calls.push(ep.id);return ep.id==='primary'?{...healthy(),connectivity:false}:healthy()},{registry:reg}); calls.length=0; await resolveSource(id,async ep=>{calls.push(ep.id);return healthy()},{registry:reg}); assert.equal(calls[0],'fallback'); assert.equal(getOperationalMetadata(id)?.lastHealthyEndpoint,'fallback'); });
test('discovered candidate is never included among approved automatic routes', async()=>{ clearOperationalMetadata(); const {approval: _approval,...candidateEndpoint}=endpoint('candidate',1);const candidate=candidateReplacement(candidateEndpoint,['catalogue name match']); const result=await resolveSource(id,async()=>healthy(),{registry:registry([candidate.endpoint])}); assert.equal(candidate.status,'CANDIDATE_REPLACEMENT'); assert.equal(candidate.activated,false); assert.equal(result.endpoint,null); });
test('same-tier endpoint with an unapproved compatibility relationship is not activated',async()=>{clearOperationalMetadata();const primary=endpoint('primary',1);const unrelated={...endpoint('unrelated',2),compatibilityGroup:'different-dataset'};const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false}:healthy(),{registry:registry([primary,unrelated])});assert.equal(result.endpoint,null);assert.deepEqual(result.attempts.map(item=>item.status),['UNAVAILABLE','DEGRADED']);});
test('cached validation can avoid repeated catalogue/schema probes within TTL',async()=>{clearOperationalMetadata();const reg=registry([endpoint('primary',1)]);await resolveSource(id,async()=>healthy(),{registry:reg});let probes=0;const cached=await resolveSource(id,async()=>{probes++;return healthy()},{registry:reg,useCachedResolution:true});assert.equal(probes,0);assert.equal(cached.endpoint?.id,'primary');assert.ok(cached.provenance?.schemaFingerprint);});
test('schema fingerprint is deterministic across upstream field ordering',()=>{const ep=endpoint('primary',1);const a=healthy(),b={...healthy(),observedFields:[...healthy().observedFields].reverse()};assert.equal(schemaFingerprint(ep,a),schemaFingerprint(ep,b));});
test('authentication and moved endpoints remain distinct health states',async()=>{clearOperationalMetadata();const reg=registry([endpoint('primary',1)]);const auth=await resolveSource(id,async()=>({...healthy(),httpStatus:401}),{registry:reg});assert.equal(auth.status,'AUTH_REQUIRED');clearOperationalMetadata();const moved=await resolveSource(id,async()=>({...healthy(),httpStatus:410}),{registry:reg});assert.equal(moved.status,'ENDPOINT_MOVED');});
