import assert from 'node:assert/strict'; import test from 'node:test';
import { clearOperationalMetadata, getOperationalMetadata, resolveSource } from './resolver';
import { candidateReplacement } from './discovery';
import { schemaFingerprint, validateEndpointSchema } from './schemaValidator';
import { LogicalSourceId, SourceEndpoint } from './sourceTypes';
import { sourceEndpoints } from './registry';

const id: LogicalSourceId = 'BGS_DETAILED_GEOLOGY';
const endpoint = (name:string, priority:number, tier:1|2=1, approval:'APPROVED'|'CANDIDATE'='APPROVED'):SourceEndpoint => ({ id:name, logicalSourceId:id, provider:'BGS', country:'GB', coverage:'test', type:'ARCGIS_REST', url:`https://test/${name}`, priority, evidenceTier:tier, compatibilityGroup:'test', expectedCapabilities:['query'], expectedLayers:[4], requiredFieldGroups:[['LEX_D'],['RCS_D']], provenance:'test', approval });
const registry = (items:SourceEndpoint[]) => new Map([[id,items]]);
const healthy = (fields=['LEX_D','RCS_D']) => ({ connectivity:true, httpStatus:200, serviceAvailable:true, observedLayers:[4], observedFields:fields.map(name=>({name,type:'esriFieldTypeString'})), capabilities:['query'] });

test('resolver accepts a healthy primary only after service and schema validation', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async()=>healthy(),{registry:registry([endpoint('primary',1)])}); assert.equal(result.status,'HEALTHY'); assert.equal(result.endpoint?.id,'primary'); assert.ok(result.provenance?.schemaFingerprint); });
test('resolver uses an approved equivalent fallback when primary is unavailable', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false,httpStatus:503}:healthy(),{registry:registry([endpoint('primary',1),endpoint('equivalent',2)])}); assert.equal(result.status,'FALLBACK_ACTIVE'); assert.equal(result.endpoint?.id,'equivalent'); });
test('lower-tier fallback retains its lower evidence tier', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false}:healthy(),{registry:registry([endpoint('primary',1),endpoint('regional',2,2)])}); assert.equal(result.provenance?.evidenceTier,2); });
test('HTTP 200 with missing required schema is SCHEMA_CHANGED', async()=>{ clearOperationalMetadata(); const result=await resolveSource(id,async()=>healthy(['LEX_D']),{registry:registry([endpoint('primary',1)])}); assert.equal(result.status,'SCHEMA_CHANGED'); assert.equal(result.endpoint,null); });
test('rate limiting and all unavailable routes stay machine readable', async()=>{ clearOperationalMetadata(); const rate=await resolveSource(id,async()=>({...healthy(),httpStatus:429}),{registry:registry([endpoint('primary',1)])}); assert.equal(rate.status,'RATE_LIMITED'); clearOperationalMetadata(); const down=await resolveSource(id,async()=>({...healthy(),connectivity:false,httpStatus:503}),{registry:registry([endpoint('primary',1)])}); assert.equal(down.status,'UNAVAILABLE'); });
test('fingerprint changes are detected for a previously cached endpoint', async()=>{ clearOperationalMetadata(); const reg=registry([endpoint('primary',1)]); await resolveSource(id,async()=>healthy(),{registry:reg,ttlMs:0}); const changed=await resolveSource(id,async()=>({...healthy(),observedFields:[{name:'LEX_D',type:'changed'},{name:'RCS_D',type:'string'}]}),{registry:reg,ttlMs:0}); assert.equal(changed.status,'SCHEMA_CHANGED'); });
test('cached healthy endpoint is tried first within TTL but is always re-probed', async()=>{ clearOperationalMetadata(); const calls:string[]=[]; const reg=registry([endpoint('primary',1),endpoint('fallback',2)]); await resolveSource(id,async ep=>{calls.push(ep.id);return ep.id==='primary'?{...healthy(),connectivity:false}:healthy()},{registry:reg}); calls.length=0; const result=await resolveSource(id,async ep=>{calls.push(ep.id);return ep.id==='fallback'?{...healthy(),connectivity:false,httpStatus:503}:healthy()},{registry:reg}); assert.equal(calls[0],'fallback'); assert.ok(calls.includes('primary')); assert.equal(result.endpoint?.id,'primary'); assert.equal(getOperationalMetadata(id)?.lastHealthyEndpoint,'primary'); });
test('discovered candidate is never included among approved automatic routes', async()=>{ clearOperationalMetadata(); const {approval: _approval,...candidateEndpoint}=endpoint('candidate',1);const candidate=candidateReplacement(candidateEndpoint,['catalogue name match']); const result=await resolveSource(id,async()=>healthy(),{registry:registry([candidate.endpoint])}); assert.equal(candidate.status,'CANDIDATE_REPLACEMENT'); assert.equal(candidate.activated,false); assert.equal(result.endpoint,null); });
test('same-tier endpoint with an unapproved compatibility relationship is not activated',async()=>{clearOperationalMetadata();const primary=endpoint('primary',1);const unrelated={...endpoint('unrelated',2),compatibilityGroup:'different-dataset'};const result=await resolveSource(id,async ep=>ep.id==='primary'?{...healthy(),connectivity:false}:healthy(),{registry:registry([primary,unrelated])});assert.equal(result.endpoint,null);assert.deepEqual(result.attempts.map(item=>item.status),['UNAVAILABLE','DEGRADED']);});
test('schema fingerprint is deterministic and ignores unrelated optional field additions',()=>{const ep=endpoint('primary',1);const a=healthy(),b={...healthy(),observedFields:[...healthy().observedFields,{name:'OPTIONAL_NEW_FIELD',type:'string'}].reverse()};assert.equal(schemaFingerprint(ep,a),schemaFingerprint(ep,b));});
test('authentication and moved endpoints remain distinct health states',async()=>{clearOperationalMetadata();const reg=registry([endpoint('primary',1)]);const auth=await resolveSource(id,async()=>({...healthy(),httpStatus:401}),{registry:reg});assert.equal(auth.status,'AUTH_REQUIRED');clearOperationalMetadata();const moved=await resolveSource(id,async()=>({...healthy(),httpStatus:410}),{registry:reg});assert.equal(moved.status,'ENDPOINT_MOVED');});
test('layer-specific schema drift cannot be hidden by fields on another layer',()=>{const ep:SourceEndpoint={...endpoint('layered',1),expectedLayers:[3,4],requiredFieldGroups:[],layerSchemaRequirements:[{layer:4,requiredFieldGroups:[['LEX_D'],['RCS_D']]},{layer:3,requiredFieldGroups:[['LEX_D']]}]};const probe={connectivity:true,httpStatus:200,serviceAvailable:true,observedLayers:[3,4],observedFields:[{name:'LEX_D'},{name:'RCS_D'}],observedLayerSchemas:[{layer:4,fields:[{name:'LEX_D'}]},{layer:3,fields:[{name:'LEX_D'},{name:'RCS_D'}]}],capabilities:['query']};const validation=validateEndpointSchema(ep,probe);assert.equal(validation.valid,false);assert.equal(validation.missingLayerFieldGroups[0].layer,4);});
test('partial SoilGrids WMS layer availability fails closed',()=>{const ep=sourceEndpoints('SOILGRIDS_MODEL').find(item=>item.type==='WMS')!;const probe={connectivity:true,httpStatus:200,serviceAvailable:true,observedLayers:['sand_0-5cm_mean'],observedFields:[],capabilities:['GetFeatureInfo']};const validation=validateEndpointSchema(ep,probe);assert.equal(validation.valid,false);assert.ok(validation.missingLayers.length>0);});
test('registry keeps dedicated BGS borehole and hydrogeology routes',()=>{assert.match(sourceEndpoints('BGS_BOREHOLES')[0].url,/GeoIndex_Onshore\/boreholes\/MapServer$/);assert.match(sourceEndpoints('BGS_HYDROGEOLOGY')[0].url,/GeoIndex_Onshore\/hydrogeology\/MapServer$/);});
