import React, { useState } from 'react';
import { EvidenceQualityScore } from '../types';
import { ShieldCheck, ChevronDown, ChevronUp, CheckCircle2, AlertCircle, AlertTriangle } from 'lucide-react';

interface EvidenceScoreCardProps { score?: EvidenceQualityScore; language?: string; }

type Copy = {
  title: string; note: string; verified: string; modelled: string; requires: string;
  verifiedNone: string; verifiedSome: string; noEvidence: string; show: string; hide: string;
  topics: string; categories: string[];
};

const copies: Record<string, Copy> = {
  en: { title: 'Evidence available for this site', note: 'Evidence status describes what the report could substantiate — not whether the site is good or bad.', verified: 'Verified', modelled: 'Modelled', requires: 'Needs verification', verifiedNone: 'The available evidence is mainly preliminary or modelled. No source-verified records were confirmed automatically for this report.', verifiedSome: 'Some source-verified evidence is available. Modelled and unresolved items still need the checks identified in the report.', noEvidence: 'Most key questions still require verification.', show: 'See evidence by topic', hide: 'Hide evidence by topic', topics: 'Evidence by topic', categories: ['Cadastre & boundary', 'Terrain & elevation', 'Geology & groundwater', 'Infrastructure & access', 'Environment & flood', 'Planning & market'] },
  de: { title: 'Verfügbare Evidenz für diesen Standort', note: 'Der Evidenzstatus beschreibt, was der Bericht belegen konnte — nicht, ob der Standort gut oder schlecht ist.', verified: 'Verifiziert', modelled: 'Modelliert', requires: 'Prüfung erforderlich', verifiedNone: 'Die verfügbaren Informationen sind überwiegend vorläufig oder modelliert. Für diesen Bericht wurden keine Quelldaten automatisch als verifiziert bestätigt.', verifiedSome: 'Ein Teil der Informationen ist quellenverifiziert. Modellierte und offene Punkte müssen weiterhin wie im Bericht beschrieben geprüft werden.', noEvidence: 'Die meisten wesentlichen Fragen müssen noch geprüft werden.', show: 'Evidenz nach Thema anzeigen', hide: 'Evidenz nach Thema ausblenden', topics: 'Evidenz nach Thema', categories: ['Kataster & Grenze', 'Gelände & Höhe', 'Geologie & Grundwasser', 'Infrastruktur & Zugang', 'Umwelt & Hochwasser', 'Planung & Markt'] },
  pl: { title: 'Dostępne dowody dla tej lokalizacji', note: 'Status dowodów opisuje, co raport mógł potwierdzić — nie ocenia, czy działka jest dobra czy zła.', verified: 'Zweryfikowane', modelled: 'Modelowane', requires: 'Wymaga weryfikacji', verifiedNone: 'Dostępne informacje są głównie wstępne lub modelowane. W tym raporcie nie potwierdzono automatycznie żadnych danych źródłowych jako zweryfikowanych.', verifiedSome: 'Część informacji została zweryfikowana w źródłach. Dane modelowane i kwestie otwarte nadal wymagają kontroli wskazanej w raporcie.', noEvidence: 'Większość kluczowych kwestii nadal wymaga weryfikacji.', show: 'Pokaż dowody według tematu', hide: 'Ukryj dowody według tematu', topics: 'Dowody według tematu', categories: ['Kataster i granice', 'Teren i wysokość', 'Geologia i wody gruntowe', 'Infrastruktura i dostęp', 'Środowisko i powódź', 'Planowanie i rynek'] },
  es: { title: 'Evidencia disponible para este emplazamiento', note: 'El estado de la evidencia indica qué pudo respaldar el informe; no califica el terreno como bueno o malo.', verified: 'Verificada', modelled: 'Modelada', requires: 'Requiere verificación', verifiedNone: 'La evidencia disponible es principalmente preliminar o modelada. No se confirmó automáticamente ningún registro de fuente como verificado en este informe.', verifiedSome: 'Hay evidencia verificada en fuentes. Los elementos modelados y pendientes todavía requieren las comprobaciones indicadas en el informe.', noEvidence: 'La mayoría de las cuestiones clave todavía requieren verificación.', show: 'Ver evidencia por tema', hide: 'Ocultar evidencia por tema', topics: 'Evidencia por tema', categories: ['Catastro y límites', 'Terreno y elevación', 'Geología y aguas subterráneas', 'Infraestructura y acceso', 'Medio ambiente e inundación', 'Planeamiento y mercado'] },
  fr: { title: 'Preuves disponibles pour ce site', note: 'Le statut des preuves indique ce que le rapport a pu étayer ; il ne juge pas si le site est bon ou mauvais.', verified: 'Vérifiées', modelled: 'Modélisées', requires: 'À vérifier', verifiedNone: 'Les informations disponibles sont principalement préliminaires ou modélisées. Aucun enregistrement source n’a été automatiquement confirmé comme vérifié pour ce rapport.', verifiedSome: 'Certaines informations sont vérifiées par les sources. Les éléments modélisés et non résolus nécessitent encore les contrôles indiqués dans le rapport.', noEvidence: 'La plupart des questions importantes restent à vérifier.', show: 'Voir les preuves par thème', hide: 'Masquer les preuves par thème', topics: 'Preuves par thème', categories: ['Cadastre et limites', 'Terrain et altitude', 'Géologie et eaux souterraines', 'Infrastructure et accès', 'Environnement et inondation', 'Urbanisme et marché'] },
  fi: { title: 'Kohteesta saatavilla oleva näyttö', note: 'Näytön tila kertoo, mitä raportti pystyi perustelemaan — ei sitä, onko kohde hyvä vai huono.', verified: 'Vahvistettu', modelled: 'Mallinnettu', requires: 'Vaatii tarkistuksen', verifiedNone: 'Saatavilla oleva tieto on pääosin alustavaa tai mallinnettua. Tässä raportissa yhtään lähdetietoa ei vahvistettu automaattisesti varmennetuksi.', verifiedSome: 'Osa tiedoista on vahvistettu lähteistä. Mallinnetut ja avoimet kohdat vaativat edelleen raportissa mainitut tarkistukset.', noEvidence: 'Useimmat keskeiset kysymykset vaativat edelleen tarkistusta.', show: 'Näytä näyttö aiheittain', hide: 'Piilota näyttö aiheittain', topics: 'Näyttö aiheittain', categories: ['Kiinteistörajat', 'Maasto ja korkeus', 'Geologia ja pohjavesi', 'Infrastruktuuri ja pääsy', 'Ympäristö ja tulva', 'Kaavoitus ja markkina'] },
  nl: { title: 'Beschikbaar bewijs voor deze locatie', note: 'De bewijsstatus beschrijft wat het rapport kon onderbouwen — niet of het perceel goed of slecht is.', verified: 'Geverifieerd', modelled: 'Gemodelleerd', requires: 'Verificatie nodig', verifiedNone: 'De beschikbare informatie is vooral voorlopig of gemodelleerd. Voor dit rapport werden geen bronrecords automatisch als geverifieerd bevestigd.', verifiedSome: 'Een deel van het bewijs is in de bron geverifieerd. Gemodelleerde en open punten vereisen nog steeds de controles uit het rapport.', noEvidence: 'De meeste belangrijke vragen moeten nog worden geverifieerd.', show: 'Bekijk bewijs per onderwerp', hide: 'Verberg bewijs per onderwerp', topics: 'Bewijs per onderwerp', categories: ['Kadaster en grenzen', 'Terrein en hoogte', 'Geologie en grondwater', 'Infrastructuur en toegang', 'Milieu en overstroming', 'Planning en markt'] }
};

export const EvidenceScoreCard: React.FC<EvidenceScoreCardProps> = ({ score, language = 'en' }) => {
  const [expanded, setExpanded] = useState(false);
  if (!score) return null;
  const lang = language.toLowerCase().split('-')[0];
  const t = copies[lang] || copies.en;
  const b = score.breakdown;
  const summary = score.verifiedCount > 0 ? t.verifiedSome : score.modelledCount > 0 ? t.verifiedNone : t.noEvidence;
  const topics = b ? [b.cadastreAndGeometry, b.terrainAndElevation, b.geologyAndGroundwater, b.infrastructureAndAccess, b.environmentalAndFlood, b.planningAndMarket] : [];

  return <section className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-xs space-y-5">
    <div className="flex items-start gap-3 border-b border-slate-100 pb-4"><div className="h-10 w-10 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-700"><ShieldCheck className="h-5 w-5"/></div><div><h3 className="text-base font-bold text-slate-900">{t.title}</h3><p className="mt-1 text-xs text-slate-500">{t.note}</p></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
      <div className="p-3 bg-emerald-50/70 border border-emerald-200/60 rounded-xl flex items-center gap-2.5"><CheckCircle2 className="h-4 w-4 text-emerald-600 shrink-0"/><div><div className="text-lg font-bold text-emerald-950">{score.verifiedCount}</div><div className="text-[11px] text-emerald-700">{t.verified}</div></div></div>
      <div className="p-3 bg-amber-50/70 border border-amber-200/60 rounded-xl flex items-center gap-2.5"><AlertCircle className="h-4 w-4 text-amber-600 shrink-0"/><div><div className="text-lg font-bold text-amber-950">{score.modelledCount}</div><div className="text-[11px] text-amber-700">{t.modelled}</div></div></div>
      <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl flex items-center gap-2.5"><AlertTriangle className="h-4 w-4 text-slate-500 shrink-0"/><div><div className="text-lg font-bold text-slate-800">{score.unverifiedCount}</div><div className="text-[11px] text-slate-600">{t.requires}</div></div></div>
    </div>
    <p className="text-xs sm:text-sm text-slate-700 leading-relaxed bg-slate-50 rounded-xl p-3.5 border border-slate-100">{summary}</p>
    <div><button type="button" onClick={()=>setExpanded(!expanded)} className="w-full flex items-center justify-between py-2 text-xs font-bold text-indigo-700 hover:text-indigo-900"><span>{expanded?t.hide:t.show}</span>{expanded?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{expanded&&<div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-3 border-t border-slate-100">{topics.map((item,index)=><div key={t.categories[index]} className="p-3 bg-slate-50 rounded-xl border border-slate-200/60"><div className="text-xs font-bold text-slate-900">{t.categories[index]}</div><p className="mt-1 text-[11px] text-slate-600 leading-normal">{item.rationale}</p></div>)}</div>}</div>
  </section>;
};