import { EvidenceLevel } from '../types';

export type EvidenceTier = 1 | 2 | 3 | 4;
export interface BgsGeologyEvidence { available: boolean; tier: EvidenceTier; status: EvidenceLevel; unitName: string | null; lithology: string | null; geologicalAge: string | null; superficialDeposit: string | null; sourceName: string; sourceUrl: string; scale: string | null; limitation: string; }
export interface BgsGroundwaterEvidence { available: boolean; tier: EvidenceTier; status: EvidenceLevel; modelledDepth: string | null; sourceName: string; sourceUrl: string; limitation: string; }
export interface BgsBoreholeContext { available: boolean; tier: EvidenceTier; count: number; nearestDistanceKm: number | null; nearestRecordId: string | null; sourceName: string; sourceUrl: string; limitation: string; }
export interface BgsSiteEvidence { geology: BgsGeologyEvidence; groundwater: BgsGroundwaterEvidence; boreholes: BgsBoreholeContext; }

export const ukGeotechnicalDesignFallback = () => ({ bearingCapacity: 'Not available — no verified site-specific engineering data', frictionAngle: NaN, cohesion: NaN, hydraulicConductivity: 'Not available — no engineering source queried', drainageClass: 'Not available — no engineering source queried' });

type FetchLike = typeof fetch;
type ArcLayer = { id: number; name?: string };
type Endpoint = { url: string; tier: 1 | 2; scale: string; label: string };
export const BGS_ENDPOINTS = {
  detailed: 'https://map.bgs.ac.uk/arcgis/rest/services/BGS_Detailed_Geology/MapServer',
  regional: 'https://map.bgs.ac.uk/arcgis/rest/services/SDDS/Geology_625k/MapServer',
  hydrogeology: 'https://map.bgs.ac.uk/arcgis/rest/services/GeoIndex_Onshore/hydrogeology/MapServer',
  boreholes: 'https://map.bgs.ac.uk/arcgis/rest/services/GeoIndex_Onshore/boreholes/MapServer'
} as const;
type BgsEndpoints = { detailed: string; regional: string; hydrogeology: string; boreholes: string };

const unavailableGeology = (): BgsGeologyEvidence => ({ available: false, tier: 4, status: 'REQUIRES_VERIFICATION', unitName: null, lithology: null, geologicalAge: null, superficialDeposit: null, sourceName: 'British Geological Survey', sourceUrl: BGS_ENDPOINTS.detailed, scale: null, limitation: 'BGS geology services were unavailable or returned no mapped geology at the site coordinate. No geological unit was inferred.' });
const unavailableGroundwater = (): BgsGroundwaterEvidence => ({ available: false, tier: 4, status: 'REQUIRES_VERIFICATION', modelledDepth: null, sourceName: 'British Geological Survey', sourceUrl: BGS_ENDPOINTS.hydrogeology, limitation: 'No validated BGS groundwater model value was returned. A design groundwater level requires site observation.' });
const unavailableBoreholes = (): BgsBoreholeContext => ({ available: false, tier: 4, count: 0, nearestDistanceKm: null, nearestRecordId: null, sourceName: 'British Geological Survey GeoIndex', sourceUrl: BGS_ENDPOINTS.boreholes, limitation: 'No queryable nearby BGS borehole record was returned. This is not evidence that boreholes do not exist.' });
const clean = (v: unknown): string | null => typeof v === 'string' && v.trim() && !/^(null|unknown|not available)$/i.test(v.trim()) ? v.trim() : typeof v === 'number' && Number.isFinite(v) ? String(v) : null;
const property = (attrs: Record<string, unknown>, patterns: RegExp[]) => { for (const [k,v] of Object.entries(attrs)) if (patterns.some(p => p.test(k))) { const x=clean(v); if (x) return x; } return null; };
const firstAttributes = (payload: any): Record<string, unknown> | null => payload?.features?.find((f: any) => f?.attributes && Object.keys(f.attributes).length)?.attributes || null;
async function fetchJson(fetcher: FetchLike, url: string): Promise<any | null> { const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),4500); try { const r=await fetcher(url,{headers:{Accept:'application/json','User-Agent':'GeoSurvey/1.0 (BGS evidence query)'},signal:controller.signal}); return r.ok?await r.json():null; } catch { return null; } finally { clearTimeout(timeout); } }
const queryLayer = (fetcher: FetchLike, endpoint: string, layerId: number, lat: number, lng: number, distance=0) => { const params=new URLSearchParams({f:'json',geometry:distance?`${lng-distance},${lat-distance},${lng+distance},${lat+distance}`:`${lng},${lat}`,geometryType:distance?'esriGeometryEnvelope':'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:distance?'true':'false',outSR:'4326'}); return fetchJson(fetcher,`${endpoint}/${layerId}/query?${params}`); };
const layersFor = async (fetcher: FetchLike, endpoint: string): Promise<ArcLayer[]> => (await fetchJson(fetcher,`${endpoint}?f=pjson`))?.layers || [];
function geologyFrom(attrs: Record<string, unknown>, endpoint: Endpoint, superficial: string | null): BgsGeologyEvidence | null { const unitName=property(attrs,[/lex(_|ical)?_?d|lexicon|unit.?name|formation|member|rock.?unit|name/i]); const lithology=property(attrs,[/lith|rock.?type|composition|description/i]); const geologicalAge=property(attrs,[/age|period|epoch|strat/i]); if(!unitName&&!lithology&&!geologicalAge)return null; return {available:true,tier:endpoint.tier,status:'VERIFIED',unitName,lithology,geologicalAge,superficialDeposit:superficial,sourceName:`British Geological Survey — ${endpoint.label}`,sourceUrl:endpoint.url,scale:endpoint.scale,limitation:`${endpoint.scale} mapped geology at the site centre; boundaries are cartographic evidence and do not replace site investigation.`}; }
async function queryGeology(fetcher: FetchLike, endpoint: Endpoint, lat:number,lng:number){ const layers=await layersFor(fetcher,endpoint.url); const bedrock=layers.filter(l=>/bedrock|geology|lithostrat/i.test(l.name||'')); const superficialLayers=layers.filter(l=>/superficial|deposit|drift/i.test(l.name||'')); let superficial:string|null=null; for(const l of superficialLayers.slice(0,3)){const a=firstAttributes(await queryLayer(fetcher,endpoint.url,l.id,lat,lng)); if(a){superficial=property(a,[/lex|unit|formation|deposit|name|lith/i]); if(superficial)break;}} for(const l of bedrock.slice(0,5)){const a=firstAttributes(await queryLayer(fetcher,endpoint.url,l.id,lat,lng)); if(a){const g=geologyFrom(a,endpoint,superficial); if(g)return g;}} return null; }
const haversineKm=(a:number,b:number,c:number,d:number)=>{const r=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return 2*r*Math.asin(Math.sqrt(x));};
async function queryGroundwater(fetcher:FetchLike, endpoint:string,lat:number,lng:number){ const layers=await layersFor(fetcher,endpoint); const layer=layers.find(l=>/hydrogeology|groundwater|aquifer/i.test(l.name||'')); if(!layer)return unavailableGroundwater(); const a=firstAttributes(await queryLayer(fetcher,endpoint,layer.id,lat,lng)); const value=a&&property(a,[/groundwater|aquifer|hydro|productiv|flow|class|description/i]); return value?{available:true,tier:2 as EvidenceTier,status:'MODELLED' as EvidenceLevel,modelledDepth:value,sourceName:`British Geological Survey — ${layer.name}`,sourceUrl:`${endpoint}/${layer.id}`,limitation:'Regional hydrogeological context at 1:625,000 scale; not a measured parcel-specific groundwater level. Site investigation is required for design.'}:unavailableGroundwater(); }
async function queryBoreholes(fetcher:FetchLike, endpoint:string,lat:number,lng:number){ const layers=await layersFor(fetcher,endpoint); const layer=layers.find(l=>/borehole\.records|borehole|water\.wells/i.test(l.name||'')); if(!layer)return unavailableBoreholes(); const payload=await queryLayer(fetcher,endpoint,layer.id,lat,lng,0.05); const features=Array.isArray(payload?.features)?payload.features:[]; const records=features.map((f:any)=>{const x=f.geometry?.x,y=f.geometry?.y;return{id:property(f.attributes||{},[/reference|borehole.?id|record.?id|registration|^id$/i]),distance:Number.isFinite(x)&&Number.isFinite(y)?haversineKm(lat,lng,y,x):null};}).sort((a:any,b:any)=>(a.distance??Infinity)-(b.distance??Infinity)); return records.length?{available:true,tier:1 as EvidenceTier,count:records.length,nearestDistanceKm:records[0].distance,nearestRecordId:records[0].id,sourceName:'British Geological Survey GeoIndex borehole records',sourceUrl:`${endpoint}/${layer.id}`,limitation:'Nearby boreholes are contextual records only and do not establish conditions beneath the selected parcel.'}:unavailableBoreholes(); }
export async function fetchBgsSiteEvidence(lat:number,lng:number,fetcher:FetchLike=fetch,endpoints:BgsEndpoints=BGS_ENDPOINTS):Promise<BgsSiteEvidence>{ const detailed:Endpoint={url:endpoints.detailed,tier:1,scale:'1:50,000',label:'Detailed Geology'}; const regional:Endpoint={url:endpoints.regional,tier:2,scale:'1:625,000',label:'Regional Geology'}; const geology=await queryGeology(fetcher,detailed)||await queryGeology(fetcher,regional)||unavailableGeology(); const [groundwater,boreholes]=await Promise.all([queryGroundwater(fetcher,endpoints.hydrogeology,lat,lng),queryBoreholes(fetcher,endpoints.boreholes,lat,lng)]); return {geology,groundwater,boreholes}; }
