export interface GermanyBoreholeEvidence { id:string; category:string; claim:string; status:'VERIFIED'|'REQUIRES_VERIFICATION'; sourceName:string; sourceUrl:string; datasetDate:string; spatialRelationship:string; calculationMethod:string; confidence:'High'|'Medium'|'Low'; value:any; limitation:string; }

type FetchLike = typeof fetch;
const SOURCE_URL='https://services.bgr.de/arcgis/rest/services/geologie/gbl/MapServer/2';
const today=()=>new Date().toISOString().slice(0,10);
const dist=(lat1:number,lon1:number,lat2:number,lon2:number)=>{const R=6371000,d=Math.PI/180,a=Math.sin((lat2-lat1)*d/2)**2+Math.cos(lat1*d)*Math.cos(lat2*d)*Math.sin((lon2-lon1)*d/2)**2;return 2*R*Math.asin(Math.sqrt(a));};

export async function queryGermanyBoreholes(lat:number,lng:number,fetcher:FetchLike=fetch,radiusM=5000):Promise<GermanyBoreholeEvidence>{
  const params=new URLSearchParams({where:'1=1',geometry:`${lng},${lat}`,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',distance:String(radiusM),units:'esriSRUnit_Meter',outFields:'gml_ID,totalLength,SGD,MERGE_SRC',returnGeometry:'true',outSR:'4326',resultRecordCount:'50',f:'geojson'});
  try{
    const response=await fetcher(`${SOURCE_URL}/query?${params.toString()}`,{headers:{Accept:'application/geo+json,application/json'}});
    if(!response.ok) throw new Error(`HTTP ${response.status}`);
    const json:any=await response.json();
    const features=Array.isArray(json?.features)?json.features:[];
    const records=features.map((f:any)=>{const p=f?.geometry?.coordinates||[];const props=f?.properties||{};const lon=Number(p[0]),lat2=Number(p[1]);return {id:props.gml_ID||null,depthM:Number.isFinite(Number(props.totalLength))?Number(props.totalLength):null,sgd:props.SGD||null,source:props.MERGE_SRC||null,distanceM:Number.isFinite(lon)&&Number.isFinite(lat2)?Math.round(dist(lat,lng,lat2,lon)):null};}).filter((x:any)=>x.id).sort((a:any,b:any)=>(a.distanceM??Infinity)-(b.distanceM??Infinity));
    const nearest=records[0];
    return {id:'de-bgr-gbl-borehole-context',category:'Ground investigations',claim:records.length?`The BGR German Borehole Locations register returned ${records.length} published borehole record${records.length===1?'':'s'} within ${Math.round(radiusM/1000)} km; the nearest returned record is approximately ${nearest.distanceM??'unknown'} m away${Number.isFinite(nearest.depthM)?`, with a recorded total length of ${nearest.depthM} m`:''}.`:`The BGR German Borehole Locations register returned no published borehole within ${Math.round(radiusM/1000)} km of the selected coordinate.`,status:'VERIFIED',sourceName:'BGR — Deutscher Bohrungsnachweis (German Borehole Locations)',sourceUrl:SOURCE_URL,datasetDate:today(),spatialRelationship:`Official BGR borehole search within ${Math.round(radiusM/1000)} km of site centre`,calculationMethod:'BGR ArcGIS REST spatial distance query; WGS84 distance ordering of returned borehole points',confidence:records.length?'High':'Medium',value:{searchRadiusM:radiusM,count:records.length,nearestDistanceM:nearest?.distanceM??null,records:records.slice(0,20)},limitation:'The BGR register provides published borehole location and header context aggregated from participating State Geological Surveys. Nearby records are contextual observations and do not establish the stratigraphy, groundwater level or engineering parameters beneath the selected parcel.'};
  }catch(error){return {id:'de-bgr-gbl-borehole-unavailable',category:'Ground investigations',claim:'The BGR German Borehole Locations register could not be queried automatically.',status:'REQUIRES_VERIFICATION',sourceName:'BGR — Deutscher Bohrungsnachweis (German Borehole Locations)',sourceUrl:SOURCE_URL,datasetDate:today(),spatialRelationship:`Within ${Math.round(radiusM/1000)} km search window`,calculationMethod:'BGR ArcGIS REST spatial query',confidence:'Low',value:{reasonCode:'SOURCE_UNAVAILABLE',error:String(error)},limitation:'Source unavailability is not evidence that boreholes or ground investigations are absent.'};}
}
