import type { EvidenceItem, VerifiedSiteReport } from '../types';

type FetchLike = typeof fetch;
type IrelandEvidence = EvidenceItem & { reasonCode?: 'NO_DATA' | 'SOURCE_UNAVAILABLE' | 'MALFORMED_DATA' };
const GSI = 'Geological Survey Ireland (GSI)';
const BEDROCK = 'https://gsi.geodata.gov.ie/server/rest/services/Bedrock/IE_GSI_Bedrock_Geology_Datasets_100K_IE26_ITM/FeatureServer/3';
const QUATERNARY = 'https://gsi.geodata.gov.ie/server/rest/services/Quaternary/IE_GSI_Quaternary_Sediments_50K_IE26_ITM/FeatureServer/0';
const AQUIFER = 'https://gsi.geodata.gov.ie/server/rest/services/Groundwater/IE_GSI_Aquifer_Datasets_IE26_ITM/FeatureServer/2';
const VULNERABILITY = 'https://gsi.geodata.gov.ie/server/rest/services/Groundwater/IE_GSI_Groundwater_Vulnerability_40K_IE26_ITM/MapServer/0';
const BOREHOLES = 'https://gsi.geodata.gov.ie/server/rest/services/Bedrock/IE_GSI_Bedrock_Boreholes_Verified_50K_IE26_ITM/FeatureServer/0';
const LANDSLIDE = 'https://gsi.geodata.gov.ie/server/rest/services/Geohazards/IE_GSI_Landslide_Susceptibility_Classification_50K_IE26_ITM/FeatureServer/0';
const LANDSLIDE_FALLBACK = 'https://gsi.geodata.gov.ie/server/rest/services/Geohazards/IE_GSI_Landslide_Susceptibility_Classification_50K_IE26_ITM/MapServer/0';
const RADON_WMS = 'https://gis.epa.ie/geoserver/EPA/wms';
const NPWS = 'https://services-eu1.arcgis.com/Jhij7i46ouO8Cc0N/ArcGIS/rest/services/NPWSDesignatedAreas/FeatureServer';
const GZT = 'https://services.arcgis.com/NzlPQPKn5QF9v2US/arcgis/rest/services/GZT_Current_Plan/FeatureServer/0';
const NPAD = 'https://services.arcgis.com/NzlPQPKn5QF9v2US/arcgis/rest/services/IrishPlanningApplications/FeatureServer/0';
const today = () => new Date().toISOString().slice(0, 10);

function text(v: unknown): string | null { if (typeof v === 'number' && Number.isFinite(v)) return String(v); if (typeof v !== 'string') return null; const s=v.trim().replace(/\s+/g,' '); return s && !/^(null|none|unknown|n\/a)$/i.test(s) ? s : null; }
function num(v: unknown): number | null { if (typeof v === 'number' && Number.isFinite(v)) return v; if (typeof v === 'string') { const n=Number(v.replace(',','.')); return Number.isFinite(n)?n:null; } return null; }
function distM(a:number,b:number,c:number,d:number){const r=6371000,to=(x:number)=>x*Math.PI/180,dp=to(c-a),dl=to(d-b);const q=Math.sin(dp/2)**2+Math.cos(to(a))*Math.cos(to(c))*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}

function arcgisUrl(base:string,lat:number,lng:number,opts:{distanceM?:number;count?:number;returnGeometry?:boolean;outFields?:string}={}){
  const p=new URLSearchParams({f:'json',where:'1=1',geometry:`${lng},${lat}`,geometryType:'esriGeometryPoint',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:opts.outFields||'*',returnGeometry:opts.returnGeometry?'true':'false'});
  if(opts.distanceM){p.set('distance',String(opts.distanceM));p.set('units','esriSRUnit_Meter');} if(opts.count)p.set('resultRecordCount',String(opts.count));
  return `${base}/query?${p}`;
}
async function json(fetcher:FetchLike,url:string,timeout=9000):Promise<any|null>{const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetcher(url,{headers:{Accept:'application/json','User-Agent':'LandSurf/1.0 Ireland evidence'},signal:c.signal});if(!r.ok)return null;const j:any=await r.json();return j&&!j.error?j:null;}catch{return null;}finally{clearTimeout(t)}}
function unavailable(id:string,category:string,sourceName:string,sourceUrl:string,claim:string,reasonCode:'NO_DATA'|'SOURCE_UNAVAILABLE'|'MALFORMED_DATA'='NO_DATA'):IrelandEvidence{return{id,category,claim,status:'REQUIRES_VERIFICATION',sourceName,sourceUrl,datasetDate:today(),spatialRelationship:'Selected site / search vicinity',calculationMethod:'Official Irish spatial service query with fail-closed validation',confidence:'Low',limitation:'An empty or failed automated response is not evidence that the relevant condition is absent. Verify the current official map and original records before a site decision.',value:{reasonCode},reasonCode};}
async function pointFeature(fetcher:FetchLike,base:string,lat:number,lng:number){const j=await json(fetcher,arcgisUrl(base,lat,lng,{count:5}));return j===null?null:Array.isArray(j.features)?j.features:[];}

async function geology(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{
  const fs=await pointFeature(fetcher,BEDROCK,lat,lng); if(fs===null)return unavailable('ie-gsi-bedrock-unavailable','Mapped bedrock geology',GSI,BEDROCK,'GSI bedrock geology could not be queried.','SOURCE_UNAVAILABLE'); if(!fs.length)return unavailable('ie-gsi-bedrock-no-data','Mapped bedrock geology',GSI,BEDROCK,'GSI returned no 1:100,000 bedrock polygon at the selected coordinate.');
  const a=fs[0].attributes||{},unit=text(a.UNIT_NAME),desc=text(a.DESCRIPT),code=text(a.STRATCODE),sheet=text(a.SHEETNO); if(!unit&&!desc)return unavailable('ie-gsi-bedrock-malformed','Mapped bedrock geology',GSI,BEDROCK,'GSI returned a bedrock feature without a readable unit or description.','MALFORMED_DATA');
  return{id:'ie-gsi-bedrock',category:'Mapped bedrock geology',claim:`GSI 1:100,000 bedrock geology maps the site as ${unit||'a mapped unit'}${desc?`: ${desc}`:''}.`,status:'VERIFIED',sourceName:`${GSI} — Bedrock Geology 1:100,000`,sourceUrl:BEDROCK,datasetDate:today(),spatialRelationship:'Official bedrock polygon containing the selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query of GSI Bedrock Geology 1:100,000',confidence:'High',limitation:'Regional geological mapping does not establish rock-head depth, weathering, fractures or design parameters at the parcel.',value:{unit,description:desc,stratigraphicCode:code,sheet,scale:'1:100,000'}};
}
async function quaternary(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{const fs=await pointFeature(fetcher,QUATERNARY,lat,lng);if(fs===null)return unavailable('ie-gsi-quaternary-unavailable','Mapped superficial geology',GSI,QUATERNARY,'GSI Quaternary sediments could not be queried.','SOURCE_UNAVAILABLE');if(!fs.length)return unavailable('ie-gsi-quaternary-no-data','Mapped superficial geology',GSI,QUATERNARY,'GSI returned no Quaternary-sediment polygon at the selected coordinate.');const a=fs[0].attributes||{},material=text(a.QSED_TYPE)||text(a.LEGENDDESC),code=text(a.QSED_CODE);if(!material)return unavailable('ie-gsi-quaternary-malformed','Mapped superficial geology',GSI,QUATERNARY,'GSI returned a sediment polygon without a readable material class.','MALFORMED_DATA');return{id:'ie-gsi-quaternary',category:'Mapped superficial geology',claim:`GSI 1:50,000 Quaternary mapping identifies the near-surface sediment as ${material}.`,status:'VERIFIED',sourceName:`${GSI} — Quaternary Sediments 1:50,000`,sourceUrl:QUATERNARY,datasetDate:today(),spatialRelationship:'Official Quaternary-sediment polygon containing the selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query',confidence:'High',limitation:'Mapped Quaternary material is screening evidence, not measured parcel stratigraphy; thickness, fill and local variation require investigation.',value:{material,code,scale:'1:50,000'}};}
async function hydro(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence[]>{const [aq,vul]=await Promise.all([pointFeature(fetcher,AQUIFER,lat,lng),pointFeature(fetcher,VULNERABILITY,lat,lng)]);const out:IrelandEvidence[]=[];if(aq===null)out.push(unavailable('ie-gsi-aquifer-unavailable','Hydrogeological context',GSI,AQUIFER,'GSI bedrock aquifer mapping could not be queried.','SOURCE_UNAVAILABLE'));else if(!aq.length)out.push(unavailable('ie-gsi-aquifer-no-data','Hydrogeological context',GSI,AQUIFER,'GSI returned no bedrock-aquifer polygon at the site.'));else{const a=aq[0].attributes||{},cat=text(a.AQUIFERCAT),desc=text(a.AQUIFERDES);out.push({id:'ie-gsi-aquifer',category:'Hydrogeological context',claim:`GSI maps the site${cat?` as aquifer class ${cat}`:''}${desc?`: ${desc}`:'.'}`,status:'VERIFIED',sourceName:`${GSI} — Bedrock Aquifers 1:100,000`,sourceUrl:AQUIFER,datasetDate:today(),spatialRelationship:'Aquifer polygon containing selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query',confidence:'High',limitation:'Aquifer class is regional context and does not establish water-table depth, seasonal level, permeability or dewatering requirements at the parcel.',value:{category:cat,description:desc}});} if(vul===null)out.push(unavailable('ie-gsi-vulnerability-unavailable','Groundwater vulnerability',GSI,VULNERABILITY,'GSI groundwater vulnerability mapping could not be queried.','SOURCE_UNAVAILABLE'));else if(!vul.length)out.push(unavailable('ie-gsi-vulnerability-no-data','Groundwater vulnerability',GSI,VULNERABILITY,'GSI returned no groundwater-vulnerability polygon at the site.'));else{const a=vul[0].attributes||{},cat=text(a.VUL_CAT),desc=text(a.VUL_DESC);out.push({id:'ie-gsi-groundwater-vulnerability',category:'Groundwater vulnerability',claim:`GSI groundwater vulnerability at the selected coordinate is ${desc||cat||'mapped but unclassified'}.`,status:'VERIFIED',sourceName:`${GSI} — Groundwater Vulnerability 1:40,000`,sourceUrl:VULNERABILITY,datasetDate:today(),spatialRelationship:'Groundwater-vulnerability polygon containing selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query',confidence:'High',limitation:'Vulnerability describes susceptibility to groundwater pollution based on subsoil depth/permeability and karst context; it is not a groundwater-depth measurement.',value:{category:cat,description:desc}});}return out;}
async function boreholes(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{const url=arcgisUrl(BOREHOLES,lat,lng,{distanceM:5000,count:50,returnGeometry:true,outFields:'HOLE_ID,LENGTH_M,COUNTY,DATASOURCE,COMMENTS,LOG_URL'}),j=await json(fetcher,url);if(!j)return unavailable('ie-gsi-boreholes-unavailable','Nearby boreholes',GSI,BOREHOLES,'GSI verified boreholes could not be queried.','SOURCE_UNAVAILABLE');const fs=Array.isArray(j.features)?j.features:[];const records=fs.map((f:any)=>{const a=f.attributes||{},x=num(f.geometry?.x),y=num(f.geometry?.y);return{id:text(a.HOLE_ID),lengthM:num(a.LENGTH_M),county:text(a.COUNTY),dataSource:text(a.DATASOURCE),logUrl:text(a.LOG_URL),distanceM:x!==null&&y!==null?Math.round(distM(lat,lng,y,x)):null};}).filter((x:any)=>x.id).sort((a:any,b:any)=>(a.distanceM??Infinity)-(b.distanceM??Infinity));return{id:'ie-gsi-boreholes',category:'Nearby boreholes',claim:records.length?`GSI returned ${records.length} verified bedrock borehole record${records.length===1?'':'s'} within 5 km; nearest approximately ${records[0].distanceM??'unknown'} m away.`:'GSI returned no verified bedrock borehole within the 5 km automated search radius.',status:'VERIFIED',sourceName:`${GSI} — Verified Bedrock Boreholes 1:50,000`,sourceUrl:BOREHOLES,datasetDate:today(),spatialRelationship:'Official verified-borehole search within 5 km of selected coordinate',calculationMethod:'ArcGIS REST distance query; WGS84 geodesic ordering of returned point records',confidence:'High',limitation:'Nearby borehole depths and logs are contextual observations only and do not prove corresponding stratigraphy or rock-head depth beneath the parcel.',value:{searchRadiusM:5000,records:records.slice(0,20),nearestDistanceM:records[0]?.distanceM??null}};}
async function landslide(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{let fs=await pointFeature(fetcher,LANDSLIDE,lat,lng);let sourceUrl=LANDSLIDE;if(fs===null){fs=await pointFeature(fetcher,LANDSLIDE_FALLBACK,lat,lng);sourceUrl=LANDSLIDE_FALLBACK;}if(fs===null)return unavailable('ie-gsi-landslide-unavailable','Landslide susceptibility',GSI,LANDSLIDE,'GSI landslide susceptibility could not be queried.','SOURCE_UNAVAILABLE');if(!fs.length)return unavailable('ie-gsi-landslide-no-data','Landslide susceptibility',GSI,sourceUrl,'GSI returned no susceptibility polygon at the selected coordinate.');const a=fs[0].attributes||{},level=text(a.LSSUSDESC),cls=text(a.LSSUSCLASS);return{id:'ie-gsi-landslide',category:'Landslide susceptibility',claim:`GSI 1:50,000 landslide susceptibility classifies the site as ${level||cls||'mapped'}.`,status:'VERIFIED',sourceName:`${GSI} — Landslide Susceptibility 1:50,000`,sourceUrl,datasetDate:today(),spatialRelationship:'Susceptibility polygon containing selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query',confidence:'High',limitation:'Susceptibility mapping is screening evidence and does not demonstrate slope stability or replace site-specific geotechnical assessment.',value:{level,classification:cls}};}
async function radon(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{const d=.002,p=new URLSearchParams({service:'WMS',version:'1.1.1',request:'GetFeatureInfo',layers:'EPA:RadonRiskMapofIreland',query_layers:'EPA:RadonRiskMapofIreland',srs:'EPSG:4326',bbox:`${lng-d},${lat-d},${lng+d},${lat+d}`,width:'101',height:'101',x:'50',y:'50',feature_count:'5',info_format:'application/json'}),url=`${RADON_WMS}?${p}`,j=await json(fetcher,url);if(!j)return unavailable('ie-epa-radon-unavailable','Radon potential','Environmental Protection Agency (EPA Ireland)',RADON_WMS,'EPA radon mapping could not be queried.','SOURCE_UNAVAILABLE');const f=Array.isArray(j.features)?j.features[0]:null,risk=text(f?.properties?.Risk);if(!risk)return unavailable('ie-epa-radon-no-data','Radon potential','Environmental Protection Agency (EPA Ireland)',RADON_WMS,'EPA returned no readable radon-risk class at the selected coordinate.');return{id:'ie-epa-radon',category:'Radon potential',claim:`EPA Ireland radon-risk mapping states: ${risk}.`,status:'VERIFIED',sourceName:'Environmental Protection Agency (EPA Ireland) — Radon Risk Map',sourceUrl:'https://www.epa.ie/environment-and-you/radon/radon-map/',datasetDate:'2026-09-15',spatialRelationship:'EPA radon-risk map class at selected coordinate',calculationMethod:'GeoServer WMS GetFeatureInfo query in EPSG:4326',confidence:'Medium',limitation:'The map predicts area-level indoor-radon risk and is not a measurement for a specific building or parcel. Testing and current building-regulation guidance remain necessary.',value:{risk}};}
async function protectedAreas(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence>{const layers=[['SPA',0],['pNHA',1],['NHA',2],['SAC',3]] as const;const results=await Promise.all(layers.map(async([type,id])=>({type,features:await pointFeature(fetcher,`${NPWS}/${id}`,lat,lng)})));if(results.every(r=>r.features===null))return unavailable('ie-npws-designations-unavailable','Protected areas','National Parks and Wildlife Service (NPWS)',NPWS,'NPWS designated-area services could not be queried.','SOURCE_UNAVAILABLE');const incomplete=results.some(r=>r.features===null);const hits=results.flatMap(r=>(r.features||[]).map((f:any)=>({type:r.type,siteCode:text(f.attributes?.SITECODE),name:text(f.attributes?.SITE_NAME)})));if(incomplete)return unavailable('ie-npws-designations-partial','Protected areas','National Parks and Wildlife Service (NPWS)',NPWS,'Only a partial set of NPWS designated-area layers responded; no definitive overlap statement is made.','SOURCE_UNAVAILABLE');return{id:'ie-npws-designations',category:'Protected areas',claim:hits.length?`The selected coordinate intersects ${hits.map(h=>`${h.type}${h.name?` ${h.name}`:''}`).join('; ')}.`:'NPWS SAC, SPA, NHA and proposed-NHA layers all responded and no designated-area polygon directly overlaps the selected coordinate.',status:'VERIFIED',sourceName:'National Parks and Wildlife Service (NPWS) — Designated Areas',sourceUrl:NPWS,datasetDate:'2026-03-03',spatialRelationship:'Direct point-in-polygon overlap check across SAC, SPA, NHA and pNHA layers',calculationMethod:'Parallel ArcGIS REST point-intersection queries of four NPWS designation layers',confidence:hits.length?'High':'Medium',limitation:'This is a direct-overlap screen only. It does not calculate distance to nearby protected sites, ecological connectivity, protected species records or project-specific Appropriate Assessment requirements.',value:{intersects:hits.length>0,hits}};}
async function planningContext(lat:number,lng:number,fetcher:FetchLike):Promise<IrelandEvidence[]>{const [gzt,apps]=await Promise.all([pointFeature(fetcher,GZT,lat,lng),json(fetcher,arcgisUrl(NPAD,lat,lng,{distanceM:1000,count:20,returnGeometry:true,outFields:'PlanningAuthority,ApplicationNumber,DevelopmentDescription,DevelopmentAddress,ApplicationStatus,Decision,ReceivedDate,GrantDate,LinkAppDetails'}))]);const out:IrelandEvidence[]=[];if(gzt===null)out.push(unavailable('ie-myplan-gzt-unavailable','Planning context','Department of Housing — MyPlan',GZT,'MyPlan generalised zoning could not be queried.','SOURCE_UNAVAILABLE'));else if(gzt.length){const a=gzt[0].attributes||{},zone=text(a.ZONE_DESC)||text(a.GZT_DESC)||text(a.ZONE_ORIG)||text(a.ZONE_GZT),plan=text(a.PLAN_NAME),authority=text(a.LA_NAME),link=text(a.ZONE_LINK);out.push({id:'ie-myplan-gzt',category:'Planning context',claim:`MyPlan generalised zoning maps the selected coordinate${zone?` as ${zone}`:''}${plan?` under ${plan}`:''}.`,status:'VERIFIED',sourceName:'Department of Housing — MyPlan Generalised Zoning Types',sourceUrl:link||GZT,datasetDate:today(),spatialRelationship:'Generalised zoning polygon containing selected coordinate',calculationMethod:'ArcGIS REST point-in-polygon query of GZT Current Plan',confidence:'Medium',limitation:'MyPlan explicitly states that generalised zoning complements rather than replaces statutory zoning and coverage is incomplete. This is preliminary planning context, not a binding zoning determination.',value:{zone,plan,authority}});}else out.push(unavailable('ie-myplan-gzt-no-data','Planning context','Department of Housing — MyPlan',GZT,'MyPlan returned no current generalised-zoning polygon at the selected coordinate.','NO_DATA'));
if(!apps)out.push(unavailable('ie-npad-unavailable','Planning application context','Department of Housing — National Planning Application Database',NPAD,'The national planning-application database could not be queried.','SOURCE_UNAVAILABLE'));else{const fs=Array.isArray(apps.features)?apps.features:[],records=fs.map((f:any)=>{const a=f.attributes||{},x=num(f.geometry?.x),y=num(f.geometry?.y);return{authority:text(a.PlanningAuthority),applicationNumber:text(a.ApplicationNumber),description:text(a.DevelopmentDescription),address:text(a.DevelopmentAddress),status:text(a.ApplicationStatus),decision:text(a.Decision),receivedDate:num(a.ReceivedDate),grantDate:num(a.GrantDate),link:text(a.LinkAppDetails),distanceM:x!==null&&y!==null?Math.round(distM(lat,lng,y,x)):null};}).sort((a:any,b:any)=>(a.distanceM??Infinity)-(b.distanceM??Infinity));out.push({id:'ie-npad-nearby-applications',category:'Planning application context',claim:records.length?`The National Planning Application Database returned ${records.length} nearby application record${records.length===1?'':'s'} within the automated 1 km search${records[0]?.distanceM!=null?`; nearest approximately ${records[0].distanceM} m away`:''}.`:'The National Planning Application Database returned no application point within the automated 1 km search radius.',status:'VERIFIED',sourceName:'Department of Housing — National Planning Application Database',sourceUrl:NPAD,datasetDate:today(),spatialRelationship:'Planning application point search within 1 km',calculationMethod:'ArcGIS REST distance query; returned records ordered by geodesic distance',confidence:'Medium',limitation:'Nearby applications provide development-history context only. They do not establish the parcel zoning, planning precedent, permission status for the selected land, or future consent.',value:{searchRadiusM:1000,records:records.slice(0,12)}});}return out;}

export async function queryIrelandNationalEvidence(lat:number,lng:number,fetcher:FetchLike=fetch):Promise<IrelandEvidence[]>{const [g,q,h,b,l,r,p,pl]=await Promise.all([geology(lat,lng,fetcher),quaternary(lat,lng,fetcher),hydro(lat,lng,fetcher),boreholes(lat,lng,fetcher),landslide(lat,lng,fetcher),radon(lat,lng,fetcher),protectedAreas(lat,lng,fetcher),planningContext(lat,lng,fetcher)]);return[g,q,...h,b,l,r,p,...pl];}

export function enrichIrelandNationalEvidence(report:VerifiedSiteReport&Record<string,any>,items:IrelandEvidence[]):void{
  const bed=items.find(i=>i.id==='ie-gsi-bedrock'&&i.status==='VERIFIED'),quat=items.find(i=>i.id==='ie-gsi-quaternary'&&i.status==='VERIFIED'),aq=items.find(i=>i.id==='ie-gsi-aquifer'&&i.status==='VERIFIED'),vul=items.find(i=>i.id==='ie-gsi-groundwater-vulnerability'&&i.status==='VERIFIED'),land=items.find(i=>i.id==='ie-gsi-landslide'&&i.status==='VERIFIED'),rad=items.find(i=>i.id==='ie-epa-radon'&&i.status==='VERIFIED'),npws=items.find(i=>i.id==='ie-npws-designations'&&i.status==='VERIFIED');
  if(bed){const v:any=bed.value||{};report.geosurvey_context={...(report.geosurvey_context||{}),geological_unit_name:v.unit||null,lithology_type:v.description||null,geological_period_era:null,evidence_level:'VERIFIED',source_name:bed.sourceName,source_url:bed.sourceUrl,source_scale:'1:100,000'};report.soil.geologicalUnit=v.unit||report.soil.geologicalUnit;report.soil.lithologyType=v.description||report.soil.lithologyType;}
  if(quat)report.geosurvey_context={...(report.geosurvey_context||{}),near_surface_material:(quat.value as any)?.material||null};
  if(aq||vul){const desc=[(aq?.value as any)?.description,(vul?.value as any)?.description?`Groundwater vulnerability: ${(vul?.value as any)?.description}`:null].filter(Boolean).join(' · ');if(desc)report.soil.groundwaterRegime=desc;report.geosurvey_context={...(report.geosurvey_context||{}),groundwater_regime:desc||null};}
  if(land&&report.terrain?.geohazards?.landslideSusceptibility){const level=String((land.value as any)?.level||'').toLowerCase();const mapped=level.includes('high')?'High':level.includes('moderate')||level.includes('medium')?'Moderate':level.includes('low')?'Low':'Not available';report.terrain.geohazards.landslideSusceptibility={...report.terrain.geohazards.landslideSusceptibility,status:'VERIFIED',level:mapped as any,description:land.claim,sourceName:land.sourceName};}
  if(rad&&report.terrain?.geohazards?.radonPotential)report.terrain.geohazards.radonPotential={...report.terrain.geohazards.radonPotential,status:'VERIFIED',classification:String((rad.value as any)?.risk||rad.claim),sourceName:rad.sourceName};
  if(npws){const v:any=npws.value||{};report.environment={...report.environment,natura2000Intersect:Boolean(v.intersects),nearestProtectedAreaName:v.hits?.[0]?.name||undefined,protectedAreaType:v.hits?.[0]?.type||undefined,status:'VERIFIED',sourceName:npws.sourceName,limitation:npws.limitation};}
}
