import { EvidenceItem } from '../types';

type FetchLike = typeof fetch;
export interface LatviaCadastreResult { success:boolean; reasonCode?:'NO_DATA'|'SOURCE_UNAVAILABLE'|'MALFORMED_DATA'; sourceName:string; sourceUrl:string; viewServiceUrl:string; viewLayer:string; viewAttribution:string; datasetDate:string; parcel?: { parcelId:string; nationalCadastralReference:string; areaM2:number|null; geometryPoints?:[number,number][] }; geometryPoints?:[number,number][]; evidence:EvidenceItem[]; limitation:string; }
const SOURCE_NAME='Valsts zemes dienests — INSPIRE Cadastral Parcels';
const WFS_URL='https://grafws.kadastrs.lv/geoserver/cp/wfs';
const WMS_URL='https://grafws.kadastrs.lv/geoserver/cp/wms';
const LAYER='cp:CadastralParcel'; const today=()=>new Date().toISOString().slice(0,10);
async function fetchJson(fetcher:FetchLike,url:string):Promise<any|null>{const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);try{const r=await fetcher(url,{headers:{Accept:'application/geo+json,application/json','User-Agent':'GroundSurf/1.0 Latvia cadastral evidence'},signal:c.signal});if(!r.ok)return null;return await r.json();}catch{return null}finally{clearTimeout(t)}}
const ring=(g:any):[number,number][]|undefined=>{const r=g?.type==='Polygon'?g.coordinates?.[0]:g?.type==='MultiPolygon'?g.coordinates?.[0]?.[0]:null;if(!Array.isArray(r))return;const out=r.map((p:any)=>[Number(p?.[1]),Number(p?.[0])] as [number,number]).filter((p:[number,number])=>Number.isFinite(p[0])&&Number.isFinite(p[1]));return out.length>=3?out:undefined};
function inside(p:[number,number],r:[number,number][]):boolean{let x=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j],c=((a[1]>p[1])!=(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/((b[1]-a[1])||Number.EPSILON)+a[0]);if(c)x=!x}return x}
function unavailable(code:LatviaCadastreResult['reasonCode'],claim:string):LatviaCadastreResult{return{success:false,reasonCode:code,sourceName:SOURCE_NAME,sourceUrl:WFS_URL,viewServiceUrl:WMS_URL,viewLayer:LAYER,viewAttribution:'© Valsts zemes dienests',datasetDate:today(),evidence:[{id:'lv-vzd-cadastre-unavailable',category:'Cadastre & identification',claim,status:'REQUIRES_VERIFICATION',sourceName:SOURCE_NAME,sourceUrl:WFS_URL,datasetDate:today(),spatialRelationship:'Selected site coordinate',calculationMethod:'Latvian INSPIRE cadastral WFS query',confidence:'Low',limitation:'No returned feature is not evidence that no parcel exists. A certified cadastral extract remains authoritative for legal boundary and rights questions.',value:{reasonCode:code}}],limitation:'No returned feature is not evidence that no parcel exists. A certified cadastral extract remains authoritative for legal boundary and rights questions.'}}
export async function queryLatviaCadastre(lat:number,lng:number,fetcher:FetchLike=fetch):Promise<LatviaCadastreResult>{const d=.001;const p=new URLSearchParams({service:'WFS',version:'2.0.0',request:'GetFeature',typeNames:LAYER,srsName:'EPSG:4326',outputFormat:'application/json',count:'10',BBOX:`${lng-d},${lat-d},${lng+d},${lat+d},EPSG:4326`});const j=await fetchJson(fetcher,`${WFS_URL}?${p}`);if(!j)return unavailable('SOURCE_UNAVAILABLE','The Latvian national cadastral WFS could not be reached or did not return valid JSON.');if(!Array.isArray(j.features))return unavailable('MALFORMED_DATA','The Latvian cadastral response did not contain a feature collection.');if(!j.features.length)return unavailable('NO_DATA','The Latvian cadastral service returned no current cadastral parcel in the immediate search envelope.');const site:[number,number]=[lat,lng];const parsed=j.features.map((f:any)=>({f,r:ring(f.geometry)})).filter((x:any)=>x.r);const chosen=parsed.find((x:any)=>inside(site,x.r))||parsed[0];if(!chosen)return unavailable('MALFORMED_DATA','The Latvian cadastral response contained no usable polygon geometry.');const pr=chosen.f.properties||{};const id=String(pr.label||pr.nationalCadastralReference||pr.localId||'').trim();if(!id)return unavailable('MALFORMED_DATA','The Latvian cadastral feature did not contain a cadastral identifier.');const area=Number(pr.areaValue??pr.AREAVALUE);const parcel={parcelId:id,nationalCadastralReference:id,areaM2:Number.isFinite(area)?area:null,geometryPoints:chosen.r};const evidence:EvidenceItem={id:'lv-vzd-cadastre',category:'Cadastre & identification',claim:`The Latvian national cadastral service identifies cadastral parcel ${id}${parcel.areaM2!==null?` with mapped area ${parcel.areaM2.toLocaleString('en-GB')} m²`:''}.`,status:'VERIFIED',sourceName:SOURCE_NAME,sourceUrl:WFS_URL,datasetDate:today(),spatialRelationship:'Current cadastral polygon containing the selected coordinate',calculationMethod:'Latvian INSPIRE CadastralParcel WFS query with local point-in-polygon selection',confidence:'High',limitation:'The map is cadastral context. Certified cadastral documentation remains authoritative for legal boundary and property-right questions.',value:parcel};return{success:true,sourceName:SOURCE_NAME,sourceUrl:WFS_URL,viewServiceUrl:WMS_URL,viewLayer:LAYER,viewAttribution:'© Valsts zemes dienests',datasetDate:today(),parcel,geometryPoints:parcel.geometryPoints,evidence:[evidence],limitation:evidence.limitation};}
export function applyLatviaCadastreToReport(report:any,result:LatviaCadastreResult,requestedAreaM2:number){if(!report)return;report.evidenceRegistry=Array.isArray(report.evidenceRegistry)?report.evidenceRegistry.filter((x:any)=>!String(x?.id||'').startsWith('lv-vzd-cadastre')):[];report.evidenceRegistry.push(...result.evidence);if(!result.success||!result.parcel)return;report.parcel={...(report.parcel||{}),status:'VERIFIED',parcelId:result.parcel.parcelId,countryCode:'LV',geometryPoints:result.parcel.geometryPoints,isOfficialGeometry:true,officialAreaM2:result.parcel.areaM2,areaCalculatedM2:requestedAreaM2,cadastralSource:SOURCE_NAME,datasetDate:result.datasetDate};report.latvia_cadastre={sourceName:result.sourceName,sourceUrl:result.sourceUrl,parcel:result.parcel,limitation:result.limitation};}
