import { VerificationRequirement } from '../types';

/** UK-specific pre-construction / due-diligence recommendations.
 * Kept separate from the Poland checklist so national terminology and authorities
 * cannot leak between country reports.
 */
export function getUKVerificationChecklist(municipality?: string, state?: string, language = 'en'): VerificationRequirement[] {
  const place = municipality || state || 'the local authority';
  const lang = String(language || 'en').toLowerCase();
  const pl = lang === 'pl';
  const de = lang === 'de';
  const planningAuthority = `${place} Local Planning Authority / Planning Department`;

  const items = pl ? [
    ['Oficjalne ustalenia planistyczne / Local Plan i pozwolenie na budowę', 'Potwierdź przeznaczenie terenu, dopuszczalne użytkowanie, parametry zabudowy, wymagania dotyczące dostępu, ograniczenia dziedzictwa oraz warunki planistyczne przed projektem architektonicznym lub nabyciem nieruchomości. Dla planowanej inwestycji uzyskaj aktualne dokumenty planistyczne i formalną analizę planistyczną zamiast polegać wyłącznie na analizie desktopowej.', `${planningAuthority}; Planning Portal / wykwalifikowany brytyjski konsultant planistyczny`, 'High'],
    ['Badanie geotechniczne i ocena stateczności gruntu', 'Dane BGS, GeoSure i otworów wiertniczych mogą wskazywać skurcz i pęcznienie gruntu, grunty ściśliwe, osuwiska, piaski płynne, skały rozpuszczalne i grunty zapadowe, ale nie określają parametrów do projektowania fundamentów. Potwierdź warstwy, wodę gruntową, warunki nośności i ryzyko przemieszczeń poprzez odpowiednie badania terenowe oraz raport geotechniczny.', 'Chartered geotechnical engineer / engineering geologist', 'High'],
    ['Ocena górnictwa, pustek podziemnych i stateczności gruntu', 'Jeżeli teren znajduje się w pobliżu historycznej eksploatacji węgla lub innych kopalin, sprawdź szyby, sztolnie, wyrobiska, kamieniołomy i inne podziemne pustki. Analiza desktopowa BGS/Coal Authority nie jest dowodem, że pod terenem nie występują pustki.', 'Coal Authority Mining Report, jeśli dotyczy; BGS / wykwalifikowany specjalista górniczy lub geotechniczny', 'High'],
    ['Ocena zanieczyszczenia terenu i historycznego użytkowania — Phase 1', 'Przeanalizuj historyczne mapy, dawne zastosowania przemysłowe, składowiska, grunty zasypane oraz potencjalnie zanieczyszczające użytkowanie w sąsiedztwie. Wskazanie w bazie historycznych składowisk jest sygnałem ryzyka, a nie dowodem zanieczyszczenia; przy prawdopodobnym związku źródło–droga–odbiorca należy wykonać odpowiednie badania terenowe.', 'Wykwalifikowany konsultant ds. zanieczyszczeń gruntu / środowiska', 'High'],
    ['Pomiary topograficzne i graniczne do celów projektowych', 'Potwierdź granice prawne, poziomy terenu, budynki, mury oporowe, odwodnienie, dostęp i widoczne sieci przed szczegółowym projektem. Granica desktopowa i model DEM nie zastępują pomiarów geodezyjnych na miejscu.', 'Chartered land surveyor / geodeta wykonujący pomiary topograficzne', 'High'],
    ['Sprawdzenie możliwości i warunków przyłączenia mediów', 'Potwierdź dostępność energii elektrycznej, wody, kanalizacji, gazu i telekomunikacji, punkty przyłączenia, przepustowość i terminy bezpośrednio u właściwych operatorów. Obecność sieci na mapie nie potwierdza dostępnej mocy ani przepustowości przyłącza.', 'Właściwi brytyjscy operatorzy sieci i przedsiębiorstwo wodociągowe; w razie potrzeby konsultant ds. mediów', 'Medium'],
    ['Weryfikacja tytułu HM Land Registry, praw i ograniczeń', 'Zweryfikuj zarejestrowany tytuł, własność, służebności, ograniczenia, prawa przejazdu, obciążenia i inne kwestie prawne przed nabyciem lub zabudową. Plan tytułu powinien być analizowany razem z rejestrem i przywołanymi dokumentami.', 'HM Land Registry; brytyjski solicitor / conveyancer ds. nieruchomości', 'High'],
    ['Ocena archeologiczna i dziedzictwa', 'Sprawdź chronione obiekty dziedzictwa oraz właściwe lokalne rejestry środowiska historycznego. Brak obiektu na National Heritage List nie wyklucza archeologii nieobjętej ochroną krajową ani lokalnego potencjału archeologicznego.', 'Local Planning Authority / Historic Environment Record; konsultant ds. dziedzictwa lub archeologii, jeśli wskazany', 'Medium']
  ] : de ? [
    ['Offizielle planungsrechtliche Stellung / Local Plan und Baugenehmigung', 'Bestätigen Sie Gebietsausweisung, zulässige Nutzung, Bebauungsparameter, Zufahrt, Denkmalschutz und Planungsauflagen vor Entwurfsplanung oder Erwerb. Für ein Vorhaben sollten die aktuellen Planungsunterlagen und eine formelle planungsrechtliche Prüfung eingeholt werden.', `${planningAuthority}; Planning Portal / qualifizierter britischer Planungskonsulent`, 'High'],
    ['Geotechnische Untersuchung und Bewertung der Baugrundstabilität', 'BGS-, GeoSure- und Bohrlochdaten können auf Schrumpf-/Quellverhalten, kompressible Böden, Rutschungen, Fließsande, lösliche Gesteine und kollabierbare Böden hinweisen. Sie ersetzen jedoch keine standortbezogene Untersuchung zur Festlegung von Gründungsparametern, Grundwasser und Tragfähigkeit.', 'Chartered geotechnical engineer / engineering geologist', 'High'],
    ['Bergbau, unterirdische Hohlräume und Baugrundstabilität', 'Bei historischer Kohle- oder anderer Rohstoffgewinnung sind Schächte, Stollen, Steinbrüche und sonstige unterirdische Hohlräume zu prüfen. Eine Desktop-Prüfung von BGS/Coal Authority beweist nicht, dass unter dem Grundstück keine Hohlräume vorhanden sind.', 'Coal Authority Mining Report, soweit zutreffend; BGS / qualifizierter Bergbau- oder Geotechnikspezialist', 'High'],
    ['Phase-1-Untersuchung zu Bodenverunreinigung und früherer Nutzung', 'Historische Karten, frühere industrielle Nutzungen, Deponien, Auffüllungen und potenziell kontaminierende Nutzungen in der Umgebung prüfen. Ein Datenbanktreffer ist ein Risikohinweis und kein Nachweis einer Kontamination; bei plausibler Schadstoffquelle sind geeignete weiterführende Untersuchungen erforderlich.', 'Qualifizierter Altlasten- / Umweltgutachter', 'High'],
    ['Topografische und Grenzvermessung für die Planung', 'Rechtliche Grenzen, Geländehöhen, Bauwerke, Stützkonstruktionen, Entwässerung, Zufahrt und sichtbare Leitungen vor der Detailplanung vermessen. Die Desktop-Grenze und das DEM ersetzen keine örtliche Vermessung.', 'Chartered land surveyor / Vermessungsingenieur', 'High'],
    ['Prüfung von Versorgungskapazität und Anschlüssen', 'Verfügbarkeit, Anschlusspunkte, Kapazität und Vorlaufzeiten für Strom, Wasser, Abwasser, Gas und Telekommunikation direkt bei den zuständigen Netz- und Versorgungsunternehmen bestätigen. Eine Leitung in einer Karte bestätigt keine Anschlusskapazität.', 'Zuständige britische Netzbetreiber und Wasserversorger; bei Bedarf Versorgungskonsulent', 'Medium'],
    ['HM Land Registry: Eigentum, Rechte und Beschränkungen', 'Registrierten Eigentumstitel, Dienstbarkeiten, Covenants, Wegerechte, Belastungen und sonstige Rechte vor Erwerb oder Entwicklung prüfen. Title Plan und Register sowie darin genannte Urkunden gemeinsam prüfen.', 'HM Land Registry; britischer Immobilien-Solicitor / Conveyancer', 'High'],
    ['Archäologie und Denkmalschutz', 'Geschützte Kulturgüter und die zuständigen lokalen Historic Environment Records prüfen. Das Fehlen eines Eintrags in der National Heritage List schließt nicht registrierte Archäologie oder lokales archäologisches Potenzial aus.', 'Local Planning Authority / Historic Environment Record; Heritage- oder Archäologieberater bei Bedarf', 'Medium']
  ] : [
    ['Official Planning Position / Local Plan & Planning Permission', 'Confirm the site allocation, permitted use, development parameters, access requirements, heritage constraints and planning conditions before architectural design or acquisition. Obtain current planning documents and a formal planning review for a proposed development.', `${planningAuthority}; Planning Portal / qualified UK planning consultant`, 'High'],
    ['Geotechnical Site Investigation & Ground Stability Assessment', 'BGS, GeoSure and borehole screening can identify potential ground hazards, but they do not establish foundation design parameters. Confirm strata, groundwater, bearing conditions and ground-movement risk through appropriate intrusive investigation and a site-specific geotechnical report.', 'Chartered geotechnical engineer / engineering geologist', 'High'],
    ['Mining, Underground Voids & Ground Stability Search', 'Where historic coal or non-coal extraction may affect the site, verify mine entries, shafts, adits, quarries and other underground workings. A desktop BGS/Coal Authority screen is not proof that no voids exist beneath the site.', 'Coal Authority Mining Report where applicable; BGS / qualified mining or geotechnical specialist', 'High'],
    ['Phase 1 Land Contamination & Historical Land-Use Assessment', 'Review historic mapping, former industrial uses, landfills, infilled ground and nearby potentially contaminative uses. A database hit is a risk indicator, not proof of contamination; plausible pollutant linkages should be investigated appropriately.', 'Qualified contaminated-land consultant / environmental consultant', 'High'],
    ['Topographical & Boundary Survey for Design', 'Confirm legal boundaries, site levels, structures, retaining features, drainage, access and visible services before detailed design. The desktop boundary and DEM are not a substitute for a measured site survey.', 'Chartered land surveyor / topographical surveyor', 'High'],
    ['Utility Capacity & Connection Enquiries', 'Confirm electricity, water, sewerage, gas and telecommunications availability, connection points, capacity and lead times directly with the relevant operators. Mapping a nearby utility does not establish connection capacity.', 'Relevant UK utility/network operators and water company; utilities consultant where required', 'Medium'],
    ['HM Land Registry Title, Rights & Restrictive Covenants', 'Verify registered title, ownership, easements, covenants, rights of way, charges and other title matters before acquisition or development.', 'HM Land Registry records reviewed by a UK property solicitor / conveyancer', 'High'],
    ['Archaeology & Heritage Screening', 'Check nationally protected heritage assets and the relevant local historic-environment records. Absence from the National Heritage List does not rule out non-designated archaeology or local archaeological potential.', 'Local planning authority / Historic Environment Record; heritage or archaeological consultant where indicated', 'Medium']
  ];

  return items.map(([topic, reason, recommendedAuthorityOrExpert, priority]) => ({ topic, reason, recommendedAuthorityOrExpert, priority: priority as 'High' | 'Medium' }));
}
